---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: home-assistant
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: disabled # skip application by Kustomize, used for replacements only
data:
  NAMESPACE: home-assistant
  REPLICATION_NAME: home-assistant-home-assistant
  PVC_NAME: home-assistant
  SECRET_NAME: restic-home-assistant-home-assistant
