# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: konflate-webhook
  namespace: konflate
type: Opaque
stringData:
  KONFLATE_WEBHOOK_SECRET: ENC[AES256_GCM,data:HEHAlYPupOuRGwXq6FL4sN3h1uRHFAZX+VGg7LLs0nHzF3/ZAMFgxl7k9dCI0inTQqcXsP5c6dPEHIoH+zejRg==,iv:uGFEuhi0CCQb+36pA4o9i5j96s0gptq2bllAU1i4tJU=,tag:Df1HY2DwvYjChn0sJE9rgg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWGhPaEk4WlUrODUrb25s
        TWljVFdMOE1tUzUvdk5WM2sxRmM5dkVzNVJzClNsekNFZ3JORlQ4bXpkd2NqQkts
        bk9HNWV3TVVJS0pPb2VES1lLaEFsUVEKLS0tIHhIM1dpa2VWaENHU2JlK3JwMWZH
        dnNFVjFQZHhlSHU0WlB0aDRZcmhoNmsK49xFaJ05CxUKNzsGLc3KBIW0uVnrnlMq
        KBs6LwhkdlQpm8TtMUn2gsBzTyFmnDwKE6TQ8BPBg0+jc5b9p/X8xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-06-07T19:36:57Z"
  mac: ENC[AES256_GCM,data:X67D5tH0wPRuNhlVHnKv/CZc5fnkojTp9n6qXjYoVH0XA4R49/XleqECvHHDTkCaY6xsgqwKbqIj9T5rvf7LNzPw0/jmYdBUVYpQAN1Ta+DcrH/N6k76hkxv9Nuz08ZPkP5i2r4SAB3P1jNhAQhulmmrEqft4KC8Gjey6IeZFfg=,iv:y4DA3T//SjDIrRyVVaHuceD4O+lX0xBb41Hl1cB6nVg=,tag:gT7uH6Me4lo0KKGkCiCQhg==,type:str]
  version: 3.13.1
