---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/httproute.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin
  namespace: pgadmin
  labels:
    ipallowlist: "true"
    auth: "required"
  annotations:
    gatus.home-operations.com/endpoint: |
      url: http://pgadmin.pgadmin.svc.cluster.local:80
      alerts:
        - type: discord
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public
      namespace: envoy-gateway-system
      sectionName: https
  hostnames:
    - pgadmin.axis.scottmckendry.tech
  rules:
    - backendRefs:
        - name: pgadmin
          port: 80
