# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secret
  namespace: databases
stringData:
  username: ENC[AES256_GCM,data:eUuZAoQZ2IA=,iv:SQGDyXEIAcc27hExJUTUbiXB5Grn9KkJ4TzhxKeTEoA=,tag:5LJEYgwVSsnTS7YtuALhpg==,type:str]
  password: ENC[AES256_GCM,data:eY32o7rFxhJL7t7j5+qYsdn+qwqnxmk1Ap5Hc2fULDY=,iv:uFy8M2553dg95iXiHw3YGbS+ESDheLCoWv4I34ZBmN8=,tag:Gxl4MSaG7Rkp1r6C7UvauA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTWFvSmpRSW82cGt4VE1B
        elh1d0l1MlQwQUhuQ094bngvejRlVzNibzFJCmF6NWhmL0l5eTU3Q01CczBzVS9I
        N0FRU0VDVVhDTFBLNEVvZXF5aVloeTAKLS0tIDRiZDRDRkVjdngyRTQyVHZiREQz
        YmVuNXJON2xQMERjMnduV2FaMVFBRDQKow7LcTaKHdgCtVrOg4zaH0XdiAXvodXb
        ax2B0gJo0rrU8urZeovTJ7pBY74Uh3CWqt+SxEjCryD4d3z5lqTQww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-05-28T07:00:28Z"
  mac: ENC[AES256_GCM,data:Son8rrGfHiMMdivn/oJsO2tKCPwPupedyWp7iL6vGWZoDwZKeyfmIPBviv5GVPWRdlTWJSeGlU8gt0sBlIgvBnCQxQXAiglCz1AFHvo4ed7x2dcHjesStTpnPyTgepAUJvwrMuup7pe63kE0o1AM/4Gf9POggLOm87uEPIqTwKI=,iv:fLk514XLFj435MzotFUZ15ZN/hcpOTIVk/CpEARAWkM=,tag:SnTsaOBgDqGNjbaxXA2+JQ==,type:str]
  version: 3.13.1
