---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea-mirror
  namespace: gitea
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      gitea-mirror:
        containers:
          app:
            image:
              repository: ghcr.io/raylabshq/gitea-mirror
              tag: v3.8.8
            env:
              BETTER_AUTH_URL: https://gitea-mirror.axis.scottmckendry.tech
              BETTER_AUTH_TRUSTED_ORIGINS: https://gitea-mirror.axis.scottmckendry.tech
              PUBLIC_BETTER_AUTH_URL: https://gitea-mirror.axis.scottmckendry.tech
              NODE_ENV: production
              DATABASE_URL: file:data/gitea-mirror.db
              HOST: 0.0.0.0
              PORT: 4321
              GITEA_MIRROR_INTERVAL: 24h
            envFrom:
              - secretRef:
                  name: gitea-mirror-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: 4321
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
    service:
      app:
        controller: gitea-mirror
        ports:
          http:
            port: 4321
    persistence:
      data:
        existingClaim: gitea-mirror-data
        globalMounts:
          - path: /app/data
