---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      version: 12.4.0
      sourceRef:
        kind: HelmRepository
        name: gitea
  interval: 1h
  timeout: 10m
  values:
    postgresql-ha:
      enabled: false
    valkey-cluster:
      enabled: false
    postgresql:
      enabled: true
    valkey:
      enabled: true

    gitea:
      admin:
        existingSecret: gitea-secrets
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      config:
        indexer:
          REPO_INDEXER_ENABLED: true
          ISSUE_INDEXER_TYPE: bleve
        server:
          ROOT_URL: https://git.axis.scottmckendry.tech
      podAnnotations: {}

    image:
      rootless: true
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch

    persistence:
      enabled: true
      claimName: gitea-data
      create: false

    service:
      http:
        type: ClusterIP
        port: 3000

    ingress:
      enabled: false # Using Traefik IngressRoute

    securityContext:
      capabilities:
        drop:
          - ALL
