creation_rules:
    - path_regex: "^.*(secret|sops).ya?ml$"
      encrypted_regex: "^.*(id|key|secret|password|token|passphrase|ca|crt|pem).*$"
      age: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
