---
creation_rules:
  - path_regex: "kubernetes/.*?(secret|sops).ya?ml$"
    encrypted_regex: "^(data|stringData|email|host|apiKey)$"
    age: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und

  - path_regex: "talos/.*?(secret|sops).ya?ml$"
    encrypted_regex: "^.*(id|key|secret|password|token|passphrase|ca|crt|pem).*$"
    age: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und

stores:
  yaml:
    indent: 2
