version: 3

vars:
  CLUSTER_NAME: "axis"
  CLUSTER_VIP: "10.0.10.10"
  TALOS_VERSION: "v1.9.5"

tasks:
  encrypt:
    desc: Encrypt all secret files with SOPS
    cmds:
      - ./scripts/sops.sh encrypt

  decrypt:
    desc: Decrypt all secret files with SOPS
    cmds:
      - ./scripts/sops.sh decrypt

  generate:
    desc: Generate Talos config
    dir: talos
    vars:
      PATCHES:
        sh: "ls patches/*.yaml 2>/dev/null | sed 's/.*/--config-patch @&/g' | tr '\n' ' '"
      IMAGE_SCHEMATIC_ID:
        sh: "curl -fsSL -X POST --data-binary @image-schematic.yaml https://factory.talos.dev/schematics | jq -r '.id'"
    cmds:
      - task: decrypt
      - cmd: mkdir -p rendered/
        silent: true
      - >
        talosctl gen config {{.CLUSTER_NAME}} https://{{.CLUSTER_VIP}}:6443
        --talos-version {{.TALOS_VERSION}}
        --install-image factory.talos.dev/installer/{{.IMAGE_SCHEMATIC_ID}}:{{.TALOS_VERSION}}
        --with-secrets talos.secret.yaml
        --output-types controlplane
        --output rendered/controlplane.yaml
        --force
        {{.PATCHES}}

  apply:
    desc: Apply Talos config
    dir: talos
    cmds:
      - task: generate
      - for: ["10.0.10.11", "10.0.10.12", "10.0.10.13"]
        cmd: talosctl apply -f rendered/controlplane.yaml -n {{.ITEM}}
