---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: traefik
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 35.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1h
  timeout: 10m
  values:
    # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
    additionalArguments:
      - --serversTransport.insecureskipverify=true

    deployment:
      enabled: true
      replicas: 3

    ports:
      web:
        redirections:
          entrypoint:
            to: websecure
            priority: 10

    service:
      enabled: true
      type: LoadBalancer
      LoadBalancerIP: 10.0.10.1
      externalTrafficPolicy: Local

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    metrics:
      prometheus:
        service:
          enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
          honorLabels: true
