---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: traefik
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 34.5.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1h
  values:
    additionalArguments:
      - --serversTransport.insecureskipverify=true

    deployment:
      enabled: true
      replicas: 3

    ports:
      web:
        redirections:
          entrypoint:
            to: websecure
            priority: 10

    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
        - 10.0.10.10
