# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: traefik
  name: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 34.5.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 1h
  values:
    ports:
      redirectTo: websecure
    persistence:
      enabled: true
      storageClass: local-path
    certificatesResolvers:
      cloudflare:
        acme:
          email: ENC[AES256_GCM,data:SDxdugVwfi9jpxTvSfw51nDYonDnlfQ/wn0=,iv:cIpVvOIiKiW9kQKbNj1FgKmqXTKmpzmq2rW8xdyGRkU=,tag:1VhDcgmun8Pa6xfhrK1+Gw==,type:str]
          storage: acme.json
          dnsChallenge:
            provider: cloudflare
            resolvers:
              - 1.1.1.1:53
              - 1.0.0.1:53
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-credentials
            key: email
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-credentials
            key: apiKey
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRkVyZWhiQWNock9QdkJz
        Q2FPaTQ5ZGhHeGVKdDYvNkxCTmVhRml2elVVCjhNUnFrSFBFYjk0RVlrZzhMUmpu
        bTl1NHBJZC92QkZSczRxZ3ZheUtjVmMKLS0tIDBQaGhVQ2x3emc2UEx2QmJ1VHBk
        Z3lqbVg1eC9aWWd5emJ6Z1gvM0lVZ00Kxt32PfelY69j7py35nZfrKF0bRW1QNIx
        LP2E3TiIdLR7XpcVtQp4KlCCHPn6bbsNviXYu+MD3TwlAgUCC2rG4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-06T08:31:44Z"
  mac: ENC[AES256_GCM,data:RvuDCspO8p8G8nLusg1FzgL0ILkrMfJxeuCKgtGZwhzOc+g6Mh/y8BaeyvyBMK0FnU/pyteLewJ3giAifFAetBfRzLF27BdeIyjDACd3LMpmO5EfX2Y9nxAKApJQm5fCml9VFCJG2EV6URHPDHMLvS8WP8sOYA5gdykjhQAlSng=,iv:TcT5bow+CL/7LIiVOQplkdeVBllILKH2XCHq41SWljk=,tag:xjZyWd0oNzpWOxTcMmySDw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email)$
  version: 3.9.4
