# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secrets
  namespace: traefik
  labels:
    app.kubernetes.io/name: tinyauth
stringData:
  APP_URL: ENC[AES256_GCM,data:jskMetxWk72Pw4WlLNsfI+M5yAPhOxgX22dOE3CniiIn89a8,iv:ftiR6s4Ku91X6eso4ddmkqu0E2Ep4oeAAEYp95vpZFQ=,tag:TARMrYSdRa+2HdOnWLiOBg==,type:str]
  SECRET: ENC[AES256_GCM,data:dqe2y5ti0jBwOIrgOHT67Ks0NfeQPwpYBLWP42Jy1GI=,iv:2d/sEa4GLKIHY5g10ikXD4jFMJYGBsZsPdyPEZndDbk=,tag:/NGr+sbACCCMiZprgROcKA==,type:str]
  GITHUB_CLIENT_ID: ENC[AES256_GCM,data:5WP7mKukyhqUHvP8yINrroeoCP0=,iv:CPojETNO8tA+HJvvEP6prgXPgCWgwwXoWDkv3nHeLuw=,tag:gOhMzV9BwAj4R5CJOySeYg==,type:str]
  GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:K7hrz3lmAat70u+D5lEigAq2RtuJ8Tz5IHkmDPmAbYfY/5cVcmuRJg==,iv:Lz1yQaFisPaqz4LPRXvXBRNlaBwlWfZ2lDdX9aoa+Wc=,tag:l7OifBB2iEliziocX+9Diw==,type:str]
  OAUTH_WHITELIST: ENC[AES256_GCM,data:7wKIVL1Sm+OCl8Dtd97W1EUXT5/3,iv:jlAD5onNTnJS+AVXwLgr7OBXsEQI8p0xO81soHfgU7I=,tag:3yN3tr9799NHovqRvWwaCw==,type:str]
  DISABLE_CONTINUE: ENC[AES256_GCM,data:RKOr4A==,iv:M4FqM6nQSsjcsbf5XUbPf3aqBtchRwNYdA+Po2A70AY=,tag:GPMIiZ0eY9x+bM95CmbECA==,type:str]
  #ENC[AES256_GCM,data:9tvMsHZH1A==,iv:YdYbIrv8SL7jeb32Zwd/FB6UwVcOATawpIe3A2GCCt0=,tag:Yw8r3rou9a6vaWxcjmM9IQ==,type:comment]
  SESSION_EXPIRY: ENC[AES256_GCM,data:PSBRO1VR,iv:P1CBsl619K0MkoPJVsvJQWmaFhJl9mTk1ruy6x6+GrE=,tag:7R4tfh+DFKMyZpG8dbG21Q==,type:str]
  APP_TITLE: ENC[AES256_GCM,data:X4xniw==,iv:O+ZntSi4lJQSfUDN4J7hukyO2/Z3faLcxn5PfQAgxfA=,tag:bBirhFnjkyjsQDQJDiQI3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZ2ZNZERGL2doNEV0cDFw
        SmZEcWQyT3MrbitpcS9rZGJ5dGpHT1Nvc3h3CmVrQitlZ0Y3a0NGZ1NYMXVGa0RF
        VUg1c1h6VFdHM3BQbFFYdk1maklUZ1UKLS0tIFhqUGZiUUtPVUVhc294a05zYXN5
        UjJXN1FwUzkrZUV4NUdzclhySnU3SXcKBh8PlmKHPQk9IpeRy4q8URJVRys/qFaS
        T5VsIDtNcibyGql+ymHigExMvgBxcHY2NUXbBZsbnjNwMz8aM0GGbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-16T08:45:22Z"
  mac: ENC[AES256_GCM,data:/PNxPnDSLMvBDUeZaZcSW0nIbJUv6byDZYda2SsCpd4uDoJdziLTe8ssw5n1/uwI9PsxeuCM81uCl4e8N78YyZYjXRj5h+vUjvGYLM3Ujukj259gXrQfCRI/o0/TyGOBOToQbkJRsiQJi+F8EsPbQXqug0JWNOZ7mEb1IXLlmvA=,iv:+Wb/MB3El+yHjPaOQte3NJ5OAxXNF0OOYwYPKkFpmM8=,tag:drCxM2lWchC7/wzUhK1Q5w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email)$
  version: 3.9.4
