# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secrets
  namespace: traefik
  labels:
    app.kubernetes.io/name: tinyauth
stringData:
  APP_URL: ENC[AES256_GCM,data:U7XSDsHy1hr23TBgI+ECDoDZcqCSGBLlkkXcAaVSwojwm96I,iv:4Bc9OGRCEugpwIdHPUyFwf5hnz93UvvkZR7yiOz3u8Y=,tag:3DZP5Qp8/BJGOFAw7G6UxA==,type:str]
  SECRET: ENC[AES256_GCM,data:rR+r1NIy3+oLkjHZlAO77wIqIhlwH9ZYGQppsnQVLU4=,iv:+JOi53CzZ1XSoTmCpzRXuI0IBMzOq/xV3EtdbYe0CZs=,tag:B3LzJR3Y22wEQXoycoNlzA==,type:str]
  GITHUB_CLIENT_ID: ENC[AES256_GCM,data:XYNK20RsTJNrx9yOTtikNAOdXW4=,iv:uuX+tsyOHcZH5Dfo+YBCuitMA+PHsOW/0neoCXLdqqY=,tag:nt4EQMSbkR1uoQLnzHK5Aw==,type:str]
  GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:/CgCmEqOuV267AKUkSzy20FdycbC9+y/npes0TGtg+AqSbSSzDMpEw==,iv:JyhO+utYtwveNErhzJCm6kAn4iwB8fi6uE1+xZcAw6s=,tag:f62G8rvpi6RiDPOlbzXdxg==,type:str]
  OAUTH_WHITELIST: ENC[AES256_GCM,data:/hmbbsAXWoYRm5FhJAAyOoilINNY,iv:8Yb/DQ+5krfNDTN7UUyWZLMJoGX3G0HnxjHXrB35xUY=,tag:F7GF/GdqHgukHgIMtqSS4w==,type:str]
  DISABLE_CONTINUE: ENC[AES256_GCM,data:Jpzy9w==,iv:pWzDDBYgGt9iikgokQx7yjjs8wgS4+m+qMs+OdT2RmY=,tag:isrPLTCJCMMzT372CmO5vw==,type:str]
  #ENC[AES256_GCM,data:As426CHoQw==,iv:2KiyYk7CSKU77azyaQc8naefuR33LZ6st9FOP1+d4uI=,tag:V88bSXx2yuzz4pLLDBfVdA==,type:comment]
  SESSION_EXPIRY: ENC[AES256_GCM,data:+VtnbabE,iv:G5XQxgAVnr8mVZuCh3Wn1EUguhNaGOxrFuQu5jhu5OI=,tag:c7LQwP6iz2ib5QI2FbuQsw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTklNeXYyZXllci9jL21s
        YWtFOVpWUG1UODlTaWk2SjY4WWsxWkg4dTE4Cis3RGF2YTNQc3pMbTRCL29iend5
        OVBHVkxJK3gycklPZ0dreVhrRmZXZlEKLS0tIEtTU3RzQ1IzWXkvSzZTMXdGVkRl
        elQrTndyRW5GTGZ2VFdacTZSSXBUcWsKENqG2T6m8pb2u/bdnHUotzGxky2wvC2q
        xr5wUXzQhLblJM0OIiTIa99FHLdvjNX7w134D+MQMYpEL3lKAGbIdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-16T04:30:20Z"
  mac: ENC[AES256_GCM,data:uasAquAN3qqllRBBpTWd1/vVMIhFqYQog2Yp2CuPRAn5tG+t49z1O/3MM126A/XhRUfC0c3PD0qe8bsVZ2jgYZDTecBH77Ou9nUwhAqaAJjaZovinkoS+CdqXarJFH+v2N3kz0Vye8D8AO6kKuPcZZABxB3IQCcQvc3LX8DQHLs=,iv:jl58s0jA56GwhDir8PCjkergwCMy4tFeW0fxEj1p254=,tag:+HcCeuIgu7HYi+SlPua2MA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email)$
  version: 3.9.4
