# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iscsi
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 1h
  timeout: 10m
  values:
    csiDriver:
      name: iscsi
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          controller-expand-secret: null
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: null
        httpConnection:
          protocol: http
          host: ENC[AES256_GCM,data:wTfvmQcDtTY=,iv:iLdptNqRBWiaFDuzzid9XgRPWO5zH30MComHP2paPxI=,tag:KQ8/swkQdzyWok4VlqsSLA==,type:str]
          port: 80
          allowInsecure: true
          apiKey: ENC[AES256_GCM,data:Liq1HEj/CVf2rEQBa9EBQCu8s4PkHRi5JziPxlrWzl7ivqM42Kc8sdjz+dCatcQY7FhTQ/pgYJmSv0XMY7iyBA4+,iv:TVJP+fpOXB2+X/k+1TSBIHW0YqwYutVzDEYiA8hhwko=,tag:YOAdCZxtoZR73HrE9jHE8Q==,type:str]
        zfs:
          datasetParentName: TrueBlue/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: TrueBlue/k8s/iscsi/s
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          zvolBlocksize: null
        iscsi:
          targetPortal: 10.0.6.1:3260
          interface: null
          namePrefix: csi-
          nameSuffix: -axis
          targetGroups:
            - targetGroupPortalGroup: 2
              targetGroupInitiatorGroup: 6
              targetGroupAuthType: None
              targetGroupAuthGroup: null
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: SSD
          extentAvailThreshold: 0
    # fix for https://github.com/democratic-csi/democratic-csi/issues/479
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    # Talos-specific config - https://github.com/democratic-csi/democratic-csi?tab=readme-ov-file#talos
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdEIrRUlOd0d0UGxicFNs
        TFpySEJBWUliZ2VEeXV6ZlplSloyMWx2K1JVCktBT3MwSEZObEZtbmo1TU51eXBh
        cXJ2YTYwUTdJSXN3Zm1wODRJN2NUelEKLS0tIHRJUEpnalJGNlcvN1lITUhwR09V
        aG1lekZzMHlIZzZHYkpMM0o3Z3ZEdlUK6NlHwyx7/zxG6G98+fadmn++9OFQgIvg
        oDZEM6in/XaPxJHLMbbH53AVr52CLSmvZxb8GwYgmSwgmhqDBdUQDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T20:15:53Z"
  mac: ENC[AES256_GCM,data:7+7RA843/eg89QzjxQHCOZKqCSh7bGz6t8EhUj8g5nv0YmmtDxrFxDUUh6HPfx+rGCfQ1FcNP86ablRToUNaPElGvotWV7YiAuvDuIthG3BPiCCg7Fe26YJIFl9qST6SiZsFtHj9ra/K7qGgmceomiyFibLz2lDdOTi+wp5QpjU=,iv:7thlDxrJiqKyMeCye2cqzYNUdOTKa7VNuZ/GeG9AwkI=,tag:VontB/6XTEAMU7rG5zoU/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.9.4
