# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iscsi
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 1h
  timeout: 10m
  values:
    csiDriver:
      name: iscsi
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          controller-expand-secret: null
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: null
        httpConnection:
          protocol: http
          host: ENC[AES256_GCM,data:HN9cN/Jnm0M=,iv:ieZ1Q57EgXchVt7oV7UhGiEvnsQ9JcFPpHiymdt/mSc=,tag:vmVJvEzLkvGrW8UOtvBl2A==,type:str]
          port: 80
          allowInsecure: true
          apiKey: ENC[AES256_GCM,data:wtZPcKGWAglveag23Uti1rcxcZxW1lKHg55LHqk1PMUo19UeHlsSDvwS9+uLyF2mB1AqTppqlZz/wag/OiV4mb1N,iv:P4I8Js6FQe8x93BYfvvRRy1SoVzvEedInTpnbZ6FHRg=,tag:oJ4Yb4XZQJR86ssarfk5MA==,type:str]
        zfs:
          datasetParentName: TrueBlue/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: TrueBlue/k8s/iscsi/s
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          zvolBlocksize: null
        iscsi:
          targetPortal: ENC[AES256_GCM,data:AUE7p6kRPteAXGjrFw==,iv:WEZPYgll8P4IC4MIEJp2wQdgaZWyigKEgrmRJ0EUXIw=,tag:mX7Y/ak7EWTyr2GCb0hzaA==,type:str]
          interface: null
          namePrefix: csi-
          nameSuffix: -axis
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 5
              targetGroupAuthType: None
              targetGroupAuthGroup: null
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: SSD
          extentAvailThreshold: 0
    # fix for https://github.com/democratic-csi/democratic-csi/issues/479
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    # Talos-specific config - https://github.com/democratic-csi/democratic-csi?tab=readme-ov-file#talos
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQVVlWlcvV0ZiRlhlbG5B
        Uk1xZm1OMkFrYlM0UzJoYmZxSW1DMGpqbjJZCkJUZHAzd3BUQ3NoeWhzSXg1ODJl
        Y1dwZUxsVjJiT3BzMnA5elRVaFJrQ0kKLS0tIEd2RDdhenpwSVpaWVFiMGJiblJZ
        VERNdE1yQjNhckdNc3p1SG43T2hLWGMK6QtADB3FuNL6+5hsRroHE2APYh/I/FmU
        iemtgzZ20QXXXHUs1tdreYzf21aXXk1jb3tfThjqKxftnU4igHNe7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-04T18:00:02Z"
  mac: ENC[AES256_GCM,data:VHWmE+6EKsx9FrYmycaUc5qt3xCLKlLw/i8/IaEqDY+CnoNZdpesNhkbIfSv/NpmaqLvMci0au0wLEWFOUPk5sASV14l65l41bJSbnvY6bwmFXbcgKujMmOd4yh7M8/ypPr7qrhgN+25wjeolESCPiFgFwcx5bs9/9hta6aSHcs=,iv:iOX5PZowZUqc/V1j+bNrWU2XXmAh2l1L/rT4y163em4=,tag:KFmXSMW1y5HtrNzsD+mb9w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey|targetPortal|shareHost)$
  version: 3.9.4
