# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iscsi
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 1h
  timeout: 10m
  values:
    csiDriver:
      name: iscsi
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          controller-expand-secret: null
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: null
        httpConnection:
          protocol: http
          host: ENC[AES256_GCM,data:A7hP1r6Z5ZI=,iv:JipE6AmWEqY0Tb1mdEXfrivy1ExXU5K2Prj9xJAHWmg=,tag:vBiuZqTXr2ar7HQPdCuYGw==,type:str]
          port: 80
          allowInsecure: true
          apiKey: ENC[AES256_GCM,data:xndwYxhPYIT7gp8OF3hyRPf6YyxI4GkSYpQfXzfiby3vCFq69d/hEWvmLxK5LrEKow2FNxQz0cPEBa7+pHbRfv7C,iv:bfk5DKqoTQvHXgSjNwGqnMETauccLbXRPFymHV+xPAU=,tag:YdBq5JrA3yDNXuJ0ricYLA==,type:str]
        zfs:
          datasetParentName: TrueBlue/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: TrueBlue/k8s/iscsi/s
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          zvolBlocksize: null
        iscsi:
          targetPortal: 10.0.6.1:3260
          interface: null
          namePrefix: csi-
          nameSuffix: -axis
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 5
              targetGroupAuthType: None
              targetGroupAuthGroup: null
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: SSD
          extentAvailThreshold: 0
    # fix for https://github.com/democratic-csi/democratic-csi/issues/479
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    # Talos-specific config - https://github.com/democratic-csi/democratic-csi?tab=readme-ov-file#talos
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTElCVTdXSUl0N01UcjNt
        RmpQNEgxdTdGOFlCTHIwR3ZxNE9LSml4cGhjCjZQc0NySEVhMUxscTc1OFQxZ1Bl
        TkV1Zll1dmlWNnExKzRVSVZzeS9pL2cKLS0tIEJNWE54U2p2UXFHSGdKbXNFendh
        SWIwZE9JL2M5bjZCMDViNlZKQ2ViOUkKgWuqi0nk0bWN1/asVSegWscEyp46gr9s
        g1K6AKyEF15AnsrgFj8Z8aXU2eGEfZZqEUQVHjaTZBwmUDv1kN06Qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T02:38:56Z"
  mac: ENC[AES256_GCM,data:lrx6xp7yQjg86963kWDxIvGFOTLMlqHDMPIWnRbCBXo68/fWS0o2lZNXzfkLeeRjE8Ac5zCdnjBaGs6oyjNXNoVJJ05oVIbbu6aVlcCUEbiaJtGmSCYPFjBckqMWLh/EmmxDDgTeI9tlQKio7tai8BrZWzOoeRWe/huPU8dL0dU=,iv:pDsNlgfnTVEtNa7y4O59XAw3X32BC1g2c4M/s8MGf6s=,tag:NDv9ElV/m7qjCW6d+8tGZA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.9.4
