# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iscsi
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 1h
  timeout: 10m
  values:
    csiDriver:
      name: iscsi
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          controller-expand-secret: null
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: null
        httpConnection:
          protocol: http
          host: ENC[AES256_GCM,data:ARc7rwMo1MU=,iv:4BPCGYdePnMAVyo2+BUUJ5gW4pkgd3DqKwnafg9PQno=,tag:Xol5lHGMWH0DGFQh3y7reA==,type:str]
          port: 80
          allowInsecure: true
          apiKey: ENC[AES256_GCM,data:vX+YGyzjttdfSvhiG26eg7PJwpg9iDwVLAQ0NSkAvtjv5LDQtmrUlcJjJ2WRBQ02HL6D0Uw9v4hWqfzeS0z+cO/c,iv:oFk/lFZLL1MKKFze2FVEtI1H4P6Wo3wWikz419l6rTk=,tag:9P/O4+P1AGa9PJgxKCzPUg==,type:str]
        zfs:
          datasetParentName: TrueBlue/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: TrueBlue/k8s/iscsi/s
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          zvolBlocksize: null
        iscsi:
          targetPortal: 10.0.6.1:3260
          interface: null
          namePrefix: csi-
          nameSuffix: -axis
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 5
              targetGroupAuthType: None
              targetGroupAuthGroup: null
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: SSD
          extentAvailThreshold: 0
    # fix for https://github.com/democratic-csi/democratic-csi/issues/479
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    # Talos-specific config - https://github.com/democratic-csi/democratic-csi?tab=readme-ov-file#talos
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR0UwY0FJeDJTMW56aWRV
        eHY0Q3FJdmVlZ01nb1B1UHBjem1OZTcxazJJCmxuMFZhZzVjclBUc3VtcjJmTXJt
        SXdtM1lLRkx5WXYwTGswUmUxaTk2Y1kKLS0tIHFrQjhEVlVvVG5xelExR0NVTTM4
        eExxbWF3b2xtY3VmdVJraEtQMGo0RkEKqLTTDqo2224etGOIRAp7yMcKUi6Ui7rK
        Wh4YB1hbVOn7DDzLNZ5H2vVsMjVwUrd8NV47UtBD6rNu5s6PDwDYFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-07T03:42:52Z"
  mac: ENC[AES256_GCM,data:Qz0S5XDnQZxurxm9myrC7CJAwYk1dcVGweg9ucMlsjlnvQSJTxXlu85ncYIcsHqLqHLr2J0yUOTEtmZy9vSf0ALL+KE33B2SpO6yMjlpNIp3N67wQt1c+AYR1VWeERyFvPWzzWwTXU8+Dn9YN6AiOwJfVNDbNbhuEwiXzeKzbcY=,iv:16Mhk1nbXdrD9Jxb249pDJAzpC7XinRJC/wjNhQzEtM=,tag:ZSzUW8Xg5/npQ5FPHxR5DA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.9.4
