# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: iscsi
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 1h
  timeout: 2m
  values:
    csiDriver:
      name: iscsi
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          controller-expand-secret: null
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: null
        httpConnection:
          protocol: http
          host: ENC[AES256_GCM,data:SokVA8lMelw=,iv:fIC4yIrv+39qedR/igwTCsvBTStJmfxkBOxJ8Te8Cew=,tag:7mL92x7PZV60KSEQcBJabQ==,type:str]
          port: 80
          allowInsecure: true
          apiKey: ENC[AES256_GCM,data:xU7Gota3XHLb23svsKp6Ly1eSiuK308LJYqLcRg5Wq2VsBW76uNXE4iKMfCtQotPn7inAjyILuFRxbu/xMOA7415,iv:9yDpST8MApjvkmjGR8zC/+qdTX/GfDNdhi8Fb+wqTvE=,tag:bsBvw9/cj2jntCJAj4SZ0g==,type:str]
        zfs:
          datasetParentName: TrueBlue/k8s/iscsi/v
          detachedSnapshotsDatasetParentName: TrueBlue/k8s/iscsi/s
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          zvolBlocksize: null
        iscsi:
          targetPortal: ENC[AES256_GCM,data:+37D4wZDqiNbYDPQmA==,iv:R238LcZ//2d4Ls/W8MJpcGugX0Y+PeWtPSreiQpq0do=,tag:DL7HCnuxg1M623Qzxp8GXA==,type:str]
          interface: null
          namePrefix: csi-
          nameSuffix: -axis
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 1
              targetGroupAuthType: None
              targetGroupAuthGroup: null
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: SSD
          extentAvailThreshold: 0
    # fix for https://github.com/democratic-csi/democratic-csi/issues/479
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    # Talos-specific config - https://github.com/democratic-csi/democratic-csi?tab=readme-ov-file#talos
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQXFOYWo0aVVLOWpQTzV4
        eDN3dFdCQ21DKzAyNkJzbHBHSXJRck5VdWlFClg0YmIrU003T1dWQ2V0Sy9pRWVS
        bUt5MGE0cDgwTXBkQ2JJMzJmN0JSWEEKLS0tIEptVTdDZWRYQnQxV2VqOVpROE1o
        czE1MDU0Mjl1WGlHLzhobUpEYXp2WlUK1tFmtWbhdpN+/kFbLLHF7FzZsoemyMt0
        JMuiBjqKEwDjuzZUB95Pnh9SIO1hPK0jSfDhcFo6lzf0C+Yff15smQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-04T17:44:47Z"
  mac: ENC[AES256_GCM,data:pw5S9IMoAUOGb6gKo1fngRruiXw9JegCx4ceMrVdjK0pWHLl0g9+/sSMQnLle0xSJHOZqtQ9GNQLf7yWpF6yKIqQboxM/Pgn5v5s4Tz9L/OEllas5GJMFhBaIBaCR0BHGhLHZnySndoNuqtXEXN5wPsZHxtpgk7/LmnD4YK4tno=,iv:Vjb5NBlD+lj7rirQsRMaqESo6cpO9Bv0ffq9RmoWQgg=,tag:2lgy5lPKLY6nn8JeQWLwHQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey|targetPortal|shareHost)$
  version: 3.9.4
