# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs
  namespace: storage
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
  interval: 1h
  timeout: 10m
  values:
    csiDriver:
      name: nfs
    storageClasses:
      - name: nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions:
          - nfsvers=4.2
          - nconnect=8
          - hard
          - noatime
          - nodiratime
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          controller-expand-secret: null
    driver:
      config:
        driver: freenas-api-nfs
        instance_id: null
        httpConnection:
          protocol: http
          host: ENC[AES256_GCM,data:J9E3iiSOxYc=,iv:MwanBelujGct6SvOanB+XID+n9NMfJ10qIoke6DBlus=,tag:EvvGQ4prVr7iNy9CfTewVQ==,type:str]
          port: 80
          allowInsecure: true
          apiKey: ENC[AES256_GCM,data:bYbWnQBGgaJkk+cCCOZjJs5npLEF9FOBQnPemrgGU48qrvjLxAd/DvAwTE9quEqbOD8Gl7VbLvnYQ2ZOM/NJJ6+C,iv:VXkSZZEUTDTPHqPP5i4XQqbG20mK0l/aaQ/UNjFYApI=,tag:LL4I/8WLcBW/tUD7QgfO2A==,type:str]
        zfs:
          datasetParentName: TrueBlue/k8s/nfs/v
          detachedSnapshotsDatasetParentName: TrueBlue/k8s/nfs/s
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          zvolBlocksize: null
        nfs:
          shareHost: ENC[AES256_GCM,data:vHnlUi/kp4Q=,iv:ibeX6b5LeRxfSsC5j5II1/Ew1ca81wZiO8+gAkQTSUw=,tag:Wjn0HIkwW64VdJfvbKmKcw==,type:str]
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
    # fix for https://github.com/democratic-csi/democratic-csi/issues/479
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSEdkU0s5RWFNSjVXMUFu
        Tk50WXFuUUlQV1pDR0ZaWi9qL0NKUmRVUWxZCng5MW53Z3VCbW80QklyY1Zmajh0
        YkVGRjQrUE84WnZNYkFncTU1ZVpkM1EKLS0tIFAvc004M0pmcURvdXdoOFN6WG5p
        V295eTczZmJzS1NIaWJIZExWWUp0UzAKwL+IjJE/Qo1q+k7YLUtAKYH0N7g/aeKg
        leHYDqoalxnMUIoTf7vy+LVwI5fv+HhdAKnCptKfl/lMCqpFfLj0fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-04T01:44:44Z"
  mac: ENC[AES256_GCM,data:/1xAZxcbwIfrwvwZ3Ydx22Ms8UIsxCLwrIkJ/gDijyhKH5GoYY70aIXa+xB07ENt9oHfqU57qPC6WhjkbvhKjAvTRUscAqwK2OYEE89eFJISejrA7XUxIv2luNtHrEjkTYv136JritJHpYCRhM+vG+8ZCgc4LaWLGcje4Cwe2Oo=,iv:oDDgayleO9uIvD8qfWGg0F5UWbA6jwYltlUMAdVjkMk=,tag:PU0KPOstqDmYjNJokGOyyQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey|targetPortal|shareHost)$
  version: 3.10.2
