# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secrets
  namespace: auth
  labels:
    app.kubernetes.io/name: tinyauth
stringData:
  TINYAUTH_APPURL: ENC[AES256_GCM,data:XUf6P5WcDyKcOfKm5wjReG/OoRi740h5QiNDpOW1Lzu7Oni6,iv:F+jGsQPc6aNTYMCH373y/hlRKejqO5jYakEV7YPc3ac=,tag:aIWv6PQ/vWwg9A1/Cz6DBQ==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ENC[AES256_GCM,data:MaCKaDSnXjRq068GPHAau0nReK8=,iv:a76xrnfvop56noOLpjCmRr1CYgucd/48HCnnMmIcYfI=,tag:MNnGF0nQC6D72HeYQAU5qQ==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:VlShrO0fTQh0Xp2cxwsrOEQdzoFbQy7UuWSVjaajaLaBNB+/JKvx7Q==,iv:frHceX135Ty2O7KPmI/aci2h9vGcnbPqoHMGyW0lH38=,tag:zKD7qMaAIl5l/uhWF4njog==,type:str]
  TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:OLBIyJTMbgNOGnqD0pJbl/ffCDhY,iv:m6KDVsrmB+3/LUI+0NwiW/9RxTJjfYPxdmW/FO6dKNM=,tag:x2QC+ilcY1adWE7LyfH/hg==,type:str]
  TINYAUTH_AUTH_SESSIONEXPIRY: ENC[AES256_GCM,data:8QD7bxmY,iv:tMO9hlzZEZSIf2ZlCQREolMlLS0JGYcB7iRtSCPeQus=,tag:/OVb2NjVAb0kVEj0Ft/mNg==,type:str]
  TINYAUTH_UI_TITLE: ENC[AES256_GCM,data:eGlnXQ==,iv:zc0b55lIhFXd/NpzR4Scx6sK+UPMNW0IJZZAqBoXaEU=,tag:MZMh24gpZ8GKnCH78PgDNg==,type:str]
  TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:YEwm27cL7uF6A9bBLr26R5yLMGGuYeaHhwrwsD3XDHkvWOhefMO9+ydRHReBxfBW55qN8cbiDbpGItqHKmMO12cx7tuZvgLSqSeY8XdLvrJJ6MCkqp/QkjWlqkFMOQs1zeA/,iv:QgH1R1VdDrIafqHLEIBAxcLvHlOPtAjr436i6lpZVwc=,tag:uewgYVFFyuBn0lP+/XwmWQ==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_CLIENTID: ENC[AES256_GCM,data:x8AvPu8bEHrU1DsRUxI9H23q8g5fpcUqHCeVAFVygLHgM87h,iv:nVH+pIu5N7c64At4fNWLIImCfBMEf3REAp6HHQKZZmI=,tag:Lyp8csqNzHVGJkA10DX69A==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_CLIENTSECRET: ENC[AES256_GCM,data:5v8FeXqYOnAB1ZLxpZ+kn5cNx+xBF6Z1/MO2YrpaTVXpq8h67tGrmKG8odzJ/bVX1oK0nQbwGu+g3nEYdPR8bQ==,iv:6RWv+MKpjvR4389wqMRDkDrn5g89IWz/nnAOIp7+JEg=,tag:1G1IzIynB/4NrpBkDWNX8A==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:Fg3eW769SEKF/hw6+DnPntuWNaIldgp4CY3lPXC0zYM/kJBqHX0QymfbApPTPFVqTX6/pMHP3IjJWIo=,iv:g9277R5pu2IZN0BPCjYFjStHk/LupJecDByQXoeWMDc=,tag:Jjh/k9wSFMnzuX+z179o3w==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_NAME: ENC[AES256_GCM,data:MFMtHkbyxg==,iv:vEzDBoVP51ogLFdM2t5Ik9ChMGYG9QULkPxoYR5eNJQ=,tag:WiKM8jZaVLDY42VBMZUQhg==,type:str]
  TINYAUTH_OIDC_PRIVATEKEYPATH: ENC[AES256_GCM,data:qRpLbI1PwEBmIUc/OMnud60hInPK7w==,iv:+jlnLJLXSUDo6REY5kCiYkFvz5IH8z8oc0RcLbxM3Zs=,tag:QoWKr7xWaGG1Kt6F8JkjvA==,type:str]
  TINYAUTH_OIDC_PUBLICKEYPATH: ENC[AES256_GCM,data:urgSdEHSlx8aElLz0LqZ3h8Ipzv+KWZtu+0=,iv:9XZopHza9aOmiBRvKCCMwBsYgjoo/70EJYfhstFN8IQ=,tag:Qfr8+wIGcKmesNmkGRQ+Kg==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTID: ENC[AES256_GCM,data:GsMweNOqLLyq8C/yAAoT5lNyuovVLnRz7BzUzK+xght7nBVN,iv:fZM1UkO2KtNu2U2y4N4tU2bMQ9lN/JvMoowBZHy6FA8=,tag:J94N3Q4incR2iJpCzlPhPg==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTSECRET: ENC[AES256_GCM,data:A25jOMpeL5Sf9agaXmlXiD6BLpyOdbmH0agm1aEhZNeL5qh92UI/QtVhN5e47B35pHM03Tlb8SqneMnCnDOirQ==,iv:jiTpU63pN7I1CIkGy1tWg7mtLlkASwFZvClxo8rBNv4=,tag:Wq7yaqP8rM5FIIKMXRI6aQ==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_NAME: ENC[AES256_GCM,data:icvAlx21VAY=,iv:Oatt3pt0BsWksWaTgerBjyDePAYZOIU6FiJGO0bLdzQ=,tag:GzLVRoN2Wswb42Y2ly1eNw==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:Si/L7EjVcoD+csISyt3ujSPZnH19ps6CQ8lYLKGRbTcMXzfiHKeDRdIjFtTAxIpfVvpybSPp,iv:1EcKAJDJ5MQOtWw15oWzHSu57/U4WxqtQsguiVVjch0=,tag:kTP941AUrQJV5sEFT0wbdg==,type:str]
  TINYAUTH_LABELPROVIDER: ENC[AES256_GCM,data:WMwuhQ==,iv:ufxcI3XEIuG0KVPHssf0UoQAPgrTm3aAl5BCbM3KeSg=,tag:ZWKciWSvM7Z5EpwUEKmerw==,type:str]
  TINYAUTH_DATABASE_DRIVER: ENC[AES256_GCM,data:n3yx2Ma+,iv:m2RtL4UKsD/mBtLENIkZd9I+q5ohQAFqxhN75ghqbFY=,tag:O+3HgdhVVQPdDerRUD7hTQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyazJ5d3dHOGN4US82ZXlU
        SDNaYm84RW1HNStTenNWUk0zTUI5Tk0yVkZzCmcxaHNtODBIdXRCbVZDWHNZVmpj
        amVSYmhPbUY3S1E1cXdPamNFK1RoRm8KLS0tIDlaU1RJUkxwZWdqZnFReVNpaGJ3
        TzR1aW9UNGc4Z3VCd0R1ZmxsdGMwaWcKCYT8A6MIWhTUfOamO9oP7LUj6MB3QXlQ
        RDKX4tWwPZhuLerJalznQGogO6mHBz29IZFK7xRYwdUNgY+QlmbLjQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-09-18T22:06:38Z"
  mac: ENC[AES256_GCM,data:DACMo1Srn1EO0doH/DsSF1SsLl2tEWtgAK4i9N87G0veXbMnPz5V32dz0eFJIUl73WHBSs5DHZfRzv5tlhXnwbVW/6okrQCxCcg6VKXivxco7eSrJI35fSCSU0U7vjyIAebKnVcVVgd3/ujSkZVP9S58UF498vxL720hyHg63sU=,iv:1wMJpnNXfyySRqyOJZqGq8cBSUEkYeGq+GC6+CHg9ZM=,tag:ktFAis6yz4VY/sRLDARubQ==,type:str]
  version: 3.13.3
