---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/configmap.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-cors
  namespace: databases
data:
  cors.ini: |
    [httpd]
    enable_cors = true

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    methods = GET,PUT,POST,HEAD,DELETE
    headers = accept,authorization,content-type,origin,referer
