# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-secret
  namespace: databases
type: Opaque
stringData:
  COUCHDB_USER: ENC[AES256_GCM,data:VEJk6JSGigqEbp0=,iv:/MIpM70J2m8wj8/V+cCSVl0/ec9he3uTlbZqP9+rb7Y=,tag:yXEX2lhzSqrBc9xXNqEk0Q==,type:str]
  COUCHDB_PASSWORD: ENC[AES256_GCM,data:u4FXytY3Cs5mVullK1Y6jums39c=,iv:Gp2FpSKS1zQrnF+YwnHzC5rtGY0JGSXlU2l/k/Z5Yts=,tag:+8UAJI7tz2w+kKFOdVV4TQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpc05FYXVxakhVTFliN2JJ
        V01USWp1ZmloZ3dvVnkzczlaaE94YmtaSEVrClVpb3kyV2hnU0NzTk9KRUh6eXZt
        d29aU09QSGtlclMzdmJCTGhMNTRjWTgKLS0tIG9VZUNVZmI2T2VZb3cwWGdmTWls
        MGw4MFNnZEVsdjFQVk9rbXQrWUsvc0kKdQuB5+eNn/pBIZg+eA9yGdxDxKc8mM9b
        3qxVq9HrR47tCJT+O1P6ZpyJirByoI9H7HWYC9J5eOi01XivBXabOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-05-24T04:15:34Z"
  mac: ENC[AES256_GCM,data:V8eH9aSYUwLA7tgguqw03Ts99qxSwC6kF+L5KQhccysm2Yb5GTchnoNRwJ0lrfaaBptsvWY8Io5a0U6pE4H5ir86Ubz4dWfvU6aPLEt+RTbOHeB8f11xajpnArBtXZghbaFNT7/NJZdV3tBMokvlke4Ao8Z0Omz2lXvofXGSSjg=,iv:NZu31mSl2F6MFR8S/Dk9xE7LLIVq48+w82S9Sfx1p4k=,tag:JLzmHZztHUANvCcEJw004A==,type:str]
  version: 3.13.1
