---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
  namespace: actual
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      actual:
        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.6.1
            ports:
              - containerPort: 5006
            env:
              - name: ACTUAL_PORT
                value: "5006"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              seccompProfile:
                type: RuntimeDefault
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - node
                      - src/scripts/health-check.js
                  initialDelaySeconds: 20
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 3
    service:
      app:
        controller: actual
        ports:
          http:
            port: 5006
    persistence:
      data:
        existingClaim: actual
