# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secrets
  namespace: traefik
  labels:
    app.kubernetes.io/name: tinyauth
stringData:
  TINYAUTH_APPURL: ENC[AES256_GCM,data:uOZ05QUgCUwp2c5FZIUzFqX2gNCLQNZAh18dfs1xkN7TiwWn,iv:h+3F2H75THxbxYDdtj7k1uk8zetwK2RtkULb6BHlNBY=,tag:ceGkKZH0MC40rf5yyr9Dww==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ENC[AES256_GCM,data:3wZmQ5fttmON5s1LxgLk8u3WuIU=,iv:3Dc7SCryAZwZtmjj6CLR4NAPN6/Z3Uba9NLU2AuTa1I=,tag:QZarZgpGOZKPPYiMl+wO3g==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:X7a89iMxcrRBYy38Da4SFgBjmAwYJ2CUTRY9XXyg8BM6BVVyOibJyw==,iv:8diYGfmUaXhofWlRyGk9Wqezb0+h9TWvH+dfhOw0R6g=,tag:2/Ubb5OK7awnS3Kx/SUR9Q==,type:str]
  TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:NT9uJ1SwUcJ4f6vsFXt3M7zaV1Qu,iv:KV8fHof+dxzAdplda7yy+nSsVfTfFJHaOzBMYblmEFc=,tag:uuVZw67knp26dZCP0BPp2w==,type:str]
  TINYAUTH_AUTH_SESSIONEXPIRY: ENC[AES256_GCM,data:w9dJCcK+,iv:0JW2uyz96p2avsJddVkTd/+f5iJnDZkQmH1L0U5ezLY=,tag:M4GBBy7eAhIj3Rnj9ssiXQ==,type:str]
  TINYAUTH_UI_TITLE: ENC[AES256_GCM,data:XDr2FA==,iv:E3BCIPi5HEUCDvjifdTP6lQ4yBS0fNlRaEYiBlTu5k4=,tag:jSsXjK22YakGgu6LKZx09Q==,type:str]
  TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:1lrHCT90OoI3kurOLnF/KDo3B2OGnPqzMD6+e/Mv7ceZ+F9rTgBhyArw/MMkl80IOlnIczHFLMe4gWjYsttZ96LtICQq4RXwqEiNZk2pBWbD0xfdVuU8eGupdyCEMCLPHHws,iv:2G+Up6Z5HA6IYV+wXmwyLTn3Taubct3sQ1gAebpu7fk=,tag:Jo5tEa/+sSnnvztfEnh6WA==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_CLIENTID: ENC[AES256_GCM,data:GxoJCTmJnq8YwSdbDnPb0ypFRyMyLzWf9dlRmHD1Ovki9kwR,iv:BQRSHwxmWZycHMuZ4qqXvSXXK+OrQIQ/vJJ5ynV5Sws=,tag:cc1wkJUXZsTTxofjiyQHHQ==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_CLIENTSECRET: ENC[AES256_GCM,data:ytA12bl4pq3XulZlgC1Mdo2ZMqVVgazGpvqMwhuiF6hxnTx7iUlDfM7S1FSvjqcCOIKmOsrMrXNEG3dfARmUMg==,iv:8+7gkjAmwTo3rP6usk4z8Ziydfou6Pt+CwPPtF4qijk=,tag:w9j6PCd15txcc6tu3XS5bw==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:+tB575mI1SLNaQOUZ9jWWBxm7YBPocpf7VyNRSTNU08F8QnhSMcikgn+9rvWtLzITKnbubgaWeC+jLY=,iv:T5nKr3/IfLfSnEk6OJNlT6NaTNYcsreQCEez8gU19B4=,tag:9C20XvlOb+fm2YgjYiFY0Q==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_NAME: ENC[AES256_GCM,data:YPGbx0YYZw==,iv:6+r/k+gPP2B5woRNk6gxkKQePHZNY/K7EY3+4v6ck3w=,tag:7C9Z79Lrkk532cnUgRYaSg==,type:str]
  TINYAUTH_OIDC_PRIVATEKEYPATH: ENC[AES256_GCM,data:OOo4Rr5zs4R4YgKtKBvGmtWKAZ8nMQ==,iv:kRDiE/ur/kvVAt07eTKzxY+sacwoeu0/WHf9UDIgBes=,tag:PYj7Csp9kBxNdPPeE7Ghsw==,type:str]
  TINYAUTH_OIDC_PUBLICKEYPATH: ENC[AES256_GCM,data:n4TLnrevCFq9yIu7usu1ruAB9XsdOc+GjW0=,iv:Q1M9I4ygiwBGCht+nDQ38T3NiA5tMpybrMKcJknl/6s=,tag:opvznWCna0xdoXJfa3RD3A==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTID: ENC[AES256_GCM,data:rxV0ozkA5kNjr2bqMbH5689YaN4xOlZu6yi+c+0YgzpFw/Oy,iv:SqNREoP8Y5w8CIjjEKTMGzfxHEU4WLnOF5jWKRRv4wo=,tag:lGZvERVM2HrUu/N9kB2uIA==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTSECRET: ENC[AES256_GCM,data:ftBirzrZIXPukM38K267ArfwTHZ1lPisj8dJqsIvlguNbykPkKpCqdk4mKkwp5zNNtfXhOtw3xZm2opGvn9Udw==,iv:OvAUwcR1zw7uuH+45GmPCIDBZataBK6IcFwWqgxbf2k=,tag:w19ocxP/1klo7yY1t5b7+A==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_NAME: ENC[AES256_GCM,data:zmR2m9oCaeY=,iv:sJYithrQbuZsgPD5FyUgpzelQLAt/YKApUXrYtlUL5o=,tag:DVbCo7MCjAaoM/ixaij1Yg==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:R2fpqSlG2wJoS0z7/puInHOZBF+6GW3ocvpnFZKJ5iPl5BomHJwoAaceqKvrEeQ3HtS0Nm1N,iv:A8YjFflr+7x5L0wFiX+XfSoptUvVo+zpKyPsD9ztsh0=,tag:K8Uu84uQ7/ABCZZ7JvaECg==,type:str]
  TINYAUTH_LABELPROVIDER: ENC[AES256_GCM,data:IKWbXA==,iv:diEqj7wjOt2mg7ywMBaQF0wqenbdts77zqpf5qBSE3Q=,tag:4DQZTh69bBjRRLjAvn4TXQ==,type:str]
  TINYAUTH_DATABASE_DRIVER: ENC[AES256_GCM,data:9ciSvFpaOUA=,iv:y4akWBT0QRpUjbnl1mYm2/41SUe7zOoCzue5rF0o4t4=,tag:L5G/xBJMs5Q5gD/anoWmLw==,type:str]
  TINYAUTH_DATABASE_PATH: ENC[AES256_GCM,data:nlGlIxSZzLerU6zJIFkvNgfhwbbZQ5f+bs4ctRHs8TsTLS5wHWx3WjVC3lDFGkNS5Q3/tJT2DDiR0caNpIiMw8fmG01ZdVMtsehppETdVO8guElrojcs+i0xPPEEgtHpGYL0zHH9Ie8JEe6fVT7uKx3I/Ro=,iv:eb3IyMaB+BEXGd24VDvV24sNJivBeKbotuscm+3e1mw=,tag:LqI+7Wiw1KJuv0PKQB/dTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ckNYTmdkMi9vdi8vREZL
        NFh0Wnp3bWtEY2VuTzhmYzFyc3AzUmNqbUQ0CkxoWXQxVVJBMlBYTTY5VnFpalpu
        M3RNNm1jTGhJbytBK1lDbXZqRE5mNUkKLS0tIGN3QnVyb3JsSTcxNUVMa3h4ajhl
        TEREcUJMdTBKSC92WWFtT0NuZXJXck0KAuzXTWb81EC6LIx4LKkQInrF+kD/Kl1b
        uT2yby/5fyod15vqQwfu3Z5q50rD7s/oxF6ekJD6zBUPwKTmC3c1mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-05-28T07:45:45Z"
  mac: ENC[AES256_GCM,data:69tA87gTxcMB54c3SX9IYrxouyRnrRwjVAU+2lNJVuFOGuIi+yR99uaCSdOXwAC0BbSCjUNCWlZd0K+2WZc0g3G+AP++crZTKa7O77dhb/rIlq7rc399HkX3UNPKTuTUjtV9DSRftlpSyYQR4+O0LnvBR3ZVw72XMokfYkrt0Jg=,iv:CgIuUcvbAC3ScGkyXkGf0YVV22c+XucFcaxGRtOp1LM=,tag:yK6nXocBEuM80yAeD0XJeA==,type:str]
  version: 3.13.1
