# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secrets
  namespace: traefik
  labels:
    app.kubernetes.io/name: tinyauth
stringData:
  TINYAUTH_APPURL: ENC[AES256_GCM,data:7nbf6rDjt7Apcd8r8Bkdu7QkETYyoms5jPCv5IVB1hvRP9BA,iv:wlKrKCZr1+uG27Ao7N3y2FjlaFNkZXKL2fJMPGeDBpc=,tag:MAHzg9i6a+SJ4EnerApPaw==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ENC[AES256_GCM,data:WEeljOwyad6hLBSREqt3y39aIJo=,iv:NJAYR2iL4QXC6ZTzpuYzB33USgB7xIXTeDsPI9330b0=,tag:tMaDwG4vQJJsCQ912r1mmQ==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:PHhmRU0NjfNs5ZJCCOfznXQnQMu5DFx7NKAta9+v2YNH/oLmf393EQ==,iv:LTXXAFhZDoyL6JA834pLWw8kNVco9+a2lOBn41tNlKI=,tag:oeqU8HZ22UUOBOqQDcsNFA==,type:str]
  TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:wzVnPCle+eIDrfIasBAxDZvAJu4p,iv:gR6aBmv8mIFzP3g71T0nEmgsSlpgi8gPtx9CtKCv3TU=,tag:ZuLcU8SqDfo+Unb6nQQusw==,type:str]
  TINYAUTH_AUTH_SESSIONEXPIRY: ENC[AES256_GCM,data:Sd4p5g+3,iv:byI/BlPJxcYUYWJ0OKoKyiZ0IsIqvfzutHthHwZZwQA=,tag:bTdnM6oUk+CXzP7ocB6h4A==,type:str]
  TINYAUTH_UI_TITLE: ENC[AES256_GCM,data:jwsQUg==,iv:6QW8COKMrVaovcjvntwFRrWr2xHHKYWfUuRH66wyZDI=,tag:zWpieo2bcE0r3JVc6vMviw==,type:str]
  TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:2NieV816HR9BGScKvit/XWemHByCuf9dm87hzjGK3ES7h+6aph/flbwKg3oR5MoSeWLz7ciL5Bc1Iqvdo7x1qJPBnqjSsTdmWB+AU7JvaQrUPViUnDhSsqyROP0UQllcR85F,iv:/zPL8DTMsnR7YCm8u8oTwd+tw9uTMoBi4Ki2BG71kCk=,tag:9BVsdfWla4pU5MxLreg0DQ==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_CLIENTID: ENC[AES256_GCM,data:S9dEcH2ntkKFfc6GATojsG+YNWk9JMk5kU/xWNfWPeaN6skz,iv:YaLrKnFBzdeho0sBVZ84It/S7wL5wFun9lWObKieWcY=,tag:ef+xB8FqKFUroBGjXw6TUg==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_CLIENTSECRET: ENC[AES256_GCM,data:u0PuB+F22KYIF9qRXp4ooYPXzo+122RZ+ZTWjc+c/XHFPG5Kl4n/jeQ9RjQP/Wtj7Rfj64CQlcjMriSZpl43xg==,iv:RYThUqo9d7//mY2RfPdzWwEMtHvVrbIDEO0ikf6Y3iA=,tag:kMBHb5hDuJFXjJcWHgC4Gg==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:MaN30vASXkkH1DCdKOHxV1To6wb1NMTqBAjszHzzDeeo22qx7w+togUQTWM06mM3Vl2m35LphiV9rrc=,iv:XG5YeRtnaf3vrl/m9uBXyni7KTtA+M5BeMV7oIlxUEQ=,tag:d5sqwBrQcvH2h99D39vYBg==,type:str]
  TINYAUTH_OIDC_CLIENTS_GRAFANA_NAME: ENC[AES256_GCM,data:6cGk7t5oRA==,iv:EIfVRC2VrIURW7+nYCrKCX2+w+wKNzwkXJ8Btfcc6VM=,tag:criLC1cK9k36sxdr69RMWw==,type:str]
  TINYAUTH_OIDC_PRIVATEKEYPATH: ENC[AES256_GCM,data:goB1kxfpUmiDABxKXeioSbK4+cgVnSs=,iv:EUv1Fnk6lr1FEM7ZRY0PUNxmwGyrhj2+iYJSJtvI5Ro=,tag:7rh3KPHovObf74v5lIkksw==,type:str]
  TINYAUTH_OIDC_PUBLICKEYPATH: ENC[AES256_GCM,data:cq4iWI4mtJ0kYmtGpB8BGyyg//ZDyoivJZnU,iv:q17ugW+MFilHnzTklNWhLq4ErIQVzWcoPwgFMaw1cB8=,tag:irzY6Nz2qmJRqee+rFuFHA==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTID: ENC[AES256_GCM,data:4OuaNyziYOvce3UAwP/cFvpGDGMPgfccfa7f1/j8GZ5ZIwe4,iv:01vVr4mFvxQcZAdIRIWF32Gk0PpEQRbxCpTgsYJIFCo=,tag:/CXi5rOzlAdVU8ZiyMv9cg==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_CLIENTSECRET: ENC[AES256_GCM,data:2XY+hOxb2xf42peDb+o09orWZwKfCErEq7tKSXNRqs8A8RafZTH5Kl4k+MVmA8zEm5CCrvggwHRo+7MhSRyRjQ==,iv:gVm/EC9c6a3Lo6Sg6eBEYs6htrIwqwegZ5f70mmQ3yE=,tag:ATkmkg2tzD8iSW6tNnh52w==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_NAME: ENC[AES256_GCM,data:Vyui7t0VnYk=,iv:RDCt8HEsar/jHYIq//CytCzZ6MzAYRXZg1bZBjHRsCA=,tag:5j28aTVuXEQRfvgpA4vUag==,type:str]
  TINYAUTH_OIDC_CLIENTS_HEADLAMP_TRUSTEDREDIRECTURIS: ENC[AES256_GCM,data:38iv4Ihnwbq7tzEnACHU0enae06ImmraaRP6zt7yC+IjbQt2QiprfxdaSq5u4vsUjUmzmn3S,iv:sy6OTjSCeqcrvFQOniHfIwC6Mn04iMupKsSX+QTmcjM=,tag:1jC8XHJu6+KuD/ouywravw==,type:str]
  TINYAUTH_LABELPROVIDER: ENC[AES256_GCM,data:Fy6u5w==,iv:p0FGTf8rvtH9eMblnECU1ycHE0oRnA2SEU0a8WQWX4Q=,tag:p6+v+kqVbUSEGwADBiZNTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM3FjSllZaUowTzMwTnVk
        anFwOGduYnRhamw0LzBEd0lpU2lTcUdsclJrCnFKeVdUNUZETXVxcmQxdHFyYjFo
        MHJmU2p0RjZVYXVpU3BQTnRqRTNoa0EKLS0tIHVlbXVRZ3pwaGxSUktDQjB1MStj
        NGg1U2lNcTVZUnBNU1RST3ZwOCt2ZEUKeXzswVOiMBJ2ATps1gliPmFvOxOef1A9
        XLJ3M7NXcwnoctkbF4TdWrj6x2Xk8cskhavArZXq7hWxQasSaYuMOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-05-27T08:41:02Z"
  mac: ENC[AES256_GCM,data:lq10dk9onhtV0lnOohucGMzIMIEtDugWisB+qhSFIeV4PzNE+gEB+mt1JFevdu4u2JtLJCYeUHVTdgMpx2bpnVLDv6ffWHKDL6uXENcK5C26IX7aVAuLd//MWEuoh7lyb/NPt9ayVcVph+WKxTLcNoSE/iZ7YDoL0EigKy04n3s=,iv:rHwleOHqi3ejAz5GFerXzhbxCQm2VX/ibKn1nF2KcvM=,tag:OW1Z0Hjwp9O6WAJWp1UL2A==,type:str]
  version: 3.13.1
