# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: tinyauth-secrets
  namespace: traefik
  labels:
    app.kubernetes.io/name: tinyauth
stringData:
  TINYAUTH_APPURL: ENC[AES256_GCM,data:WAreu5lAvMtFc0fuUkH4IhOkgSDPPIFYyh7QipXU8SSmYCQI,iv:Mm3pZ6H+gnEOtKZIp1Nq2r3au8iGB45I4P4P/5pdVs4=,tag:jognAxT9sc4XVWyfGkQeyw==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ENC[AES256_GCM,data:KZmka61NQHvbf5R/thaIzD+COFQ=,iv:jR6CI/yRMExJBUXm3/3Le/jbBWxW721/1V8wFsXsbBo=,tag:WjyjbP/Zt1Lb9//i+ucSRw==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ENC[AES256_GCM,data:ceOdwn9uRoFZvr5e6buzQcrosgEvnj5FEe0Q8pLp6MT0+hzdJC64Qw==,iv:sjH4g0B0wKwSHfhJPR7d0Vrl5Kaw34rf4s1orC5UlDQ=,tag:y21tHZUxk1xMoN+yfafuhw==,type:str]
  TINYAUTH_OAUTH_WHITELIST: ENC[AES256_GCM,data:VtNWGNSHRp+6FGUjLGKN/eCaOZ9b,iv:5I2MW/sfH/qIlBmo3BstzYI/jQkiqhoczrZ16oNfUUk=,tag:CWBOPyrBwqtDUhd8hb6i8A==,type:str]
  TINYAUTH_AUTH_SESSIONEXPIRY: ENC[AES256_GCM,data:lxOHegdB,iv:4hhBGaY6fuaMkhpZ9MA3jiCkEPyI1rebBhDjE60wW7I=,tag:2J3J5VAcx/i7PgC+dNyn0g==,type:str]
  TINYAUTH_UI_TITLE: ENC[AES256_GCM,data:zcJl7g==,iv:LzwDofbiVWcG2eIbQ8/CdwY20lKFs9+MJA5TwGX2Fh8=,tag:ytsJAI57IRQMo3ZCwunITw==,type:str]
  TINYAUTH_AUTH_USERS: ENC[AES256_GCM,data:ncO69bpeA0wHOvdQtr04SpudAM931CIfoIht+QbRNh2P1tYyUOLqgvkj4WFvFyZCFN/Ax/vI934u8YAAw7bbtJuDq6G4f0RYh4SYmsag3FH1eipIRox6Bwh0UER7YxZWMndM,iv:o12vsDnzuFh5GEfcJsMTSSfs9/FO3Gr6mg8Z+0rKTGc=,tag:YETQHRIjQ0HKapq5/x6rCw==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZTRnUlVWTmVvcmFqdmxi
        NWttV1hobGYxdWZHakhhcnVlVUxiUE00UWwwClEwV0tpazlDRU9GaUU5bGpOQVdu
        MWdHVlR0SkJyMXA0bERrNytMWkpEeVUKLS0tIE1pRkl2bGdIZUNhUWcwNmRyMUFx
        U21oREwvTzJoMGdpUzhJNDFoaHhmTW8K7sJL4JszMyMFs9Sah2Mc/zZM/kNSn0Il
        nA2IP0xNGDNPPs1AsVndyq97hvMkA+focJJykjc0GFy11R2KEnf/uA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T08:17:21Z"
  mac: ENC[AES256_GCM,data:6HbYIobYfTiy3ZkJRjhmZhbEfROTpb41acsqvuYU1yhuh0qjJteKcYuN3HCg128q2sIZwJPB0AQyR5bu6xUy1HKENWHWyLUl29HvfqBuxz9DN79i/Zgr+kK6Y/DXggKwo5h8PDTXiW9U1sUrGcSsnKiWDKBJetBkT/JvMhRgt/M=,iv:jBON3ix7OwXuQpNWDG+TfuOsf6yTAwb4YT5JVtExDjU=,tag:2Ee5nXYrv5xaoMW6++uZRw==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.12.2
