# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-gitea-gitea
  namespace: gitea
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:HXWOGFj5SDQFrb3MfOHsWafG0X+cA9zfm706AiO0gEsRIkiOs4lhj7j1G2muNUXwbevy4L0BXHL8FA==,iv:uakX1LNy/BZCjjeP4GQJyq+U2sHQhQzwOcsoTjcj40I=,tag:dgVCvnc8Nq1JwCQxvT8WTw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:bv7LNSm9i8fw+wnjVc+xLmwQUE4x3OZJh2FNkRHQI3A=,iv:Cy5f2sgl16dtEbu5BnqPVc3Ua+6zzqdXn/EKJA/cMi0=,tag:ABsdunwJB1VUwZnXm923WQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4SqElR3swZ8ktaRBx4hVLHQzSzY041OUCw==,iv:hFPiFQimogmHBBw2btcBIto9yVt9hXuzuQSSW2CbxNM=,tag:R11S8209CVkvY1Thui1B8A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:W1tMZGr7lIZtMFbg5RaKPyhPaqNPq5DOH2SsOJu1rw==,iv:n72acdCEN/cV1R4PQRFli6XOavmELH25Zc44B1wi41U=,tag:ZEQUwVZnmz1ENtsFMWlitQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWlVnOWdFTkJHOEpjQ202
        RzJ2WERjbWNRZ2wvWFY0dFpPT0NvU1dWYXo4Cm1saGE5QTljazhVcTFOWHZSdmR4
        aVJKa2taVi9vOTZXamxJVTlKZFl1UTAKLS0tIHpJL2RyNXl3YUEyL3g1amdZSFJE
        R1BuTllHUE5xazlFWlBDVE9iNWp1aUkKYMejWAdBEOdxAL0aa0xcBdS91y86o1jw
        HwDQiov54MvTaLdLyixJMyJ2l3WmRSksi1+yb7X4+eXPhQSfEp6mRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-24T23:40:38Z"
  mac: ENC[AES256_GCM,data:QXPZVzFy5XFNk4EFQgk6ELoTdh7I/GucQBi80zu9Lz5bbe9C+UO/e4E5k8cWnglke19QHcdhWpMISMF4sh5cJASHHEfaSw07Uhcz/a1gbEbxzIIBKfgh9PNq9MQ6OshArJyXZTJMDfYBNPjAwzTb4ELrePGC9+8Z7NKE1Kz7iCg=,iv:p6KxYz/cWizRBtmHOysy+/iuvD2WDxWYm2dSa4bAKyI=,tag:x07ThGhkGD+DWWGhs1hGtQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.11.0
