---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: volsync
  name: volsync
spec:
  chart:
    spec:
      chart: volsync
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: backube
  interval: 1h
  timeout: 10m
