---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-provisioner
  labels:
    pod-security.kubernetes.io/enforce: privileged
