---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: local-path-provisioner
  name: local-path-provisioner
spec:
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      version: 0.0.31
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
  interval: 1h
  values:
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/local-path-provisioner
