---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: kube-system
  name: metrics-server
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      chart: metrics-server
      version: 3.12.0
  interval: 1h
  values:
    args:
      - --kubelet-insecure-tls
