---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  namespace: kube-system
  name: metrics-server
spec:
  url: https://kubernetes-sigs.github.io/metrics-server/
  interval: 24h
