# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:QaDMxW64VqaaUH3yqKHLRO8AImHfJ+wUY2/LUojy3+Idva6m3NmgN3eA2ayhlxj3UTNOnKh64nedyehAsp6IenSQzaGA3o3Aa84ljSbn+BRvv+MvZ+F3PS2jCVHgAt8MpAat6swuPZlmfitwxThyWizQhYWrmiRxz8gFV9Q9aw==,iv:J8dt8aRGK4AE27g/3KTb1VDStNj1zldwmP77GpZYy2E=,tag:E0M5aHPCQlt9XoaOvLbMSg==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:eStxnTqRxr9h0+4fd7/G+D/R3uZ0O5Y5AddnbUSrh4E=,iv:cB18GVIkaUdMIzToH7TGMY98PnuRWofKOPoGpTmxzrs=,tag:oWw9qGKny3wAlfdoAMtAWA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcWVnTGoyQllST3MyU0dr
        TVZhQ0o2N2NpSWwyenlJakZ3ZzgrME9OeWpBCkpKM1loYTE2NWp0TjBndnR0b3Vv
        UHhCVktVc01lMk1DajkzTS9kZEFEY1EKLS0tIFUvb25OeU53SGo3M0Z2Q1BRODJB
        Z3JCSWNUZUFwd1hHa1pOai9uclBScFEKqNPmllFK7S7lRx73ofn9dO87gbOjz82+
        jekrrggU8jw1u2Kkj+p6q9V7Gt4OMAdyOPlTO6nvj6FPRp2nkBUwnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-12T03:03:26Z"
  mac: ENC[AES256_GCM,data:xNH2fH+37sOnZ5vc9TQqJzhOdSbLP2I7qDja2DPEqZuaJmy1/SXqR5nC78GQ9SNHvrFhpgOEVheMZyi+xUj5ZC1v0IxYtP4R9mWpjNstuFZueaoJSXvCaKFOKRgdRlErZLeL82tk5tKDuKvEOaVnNogmU0xulqkPCHdsul+oDuI=,iv:J0YhQ4DEHQ9a2knyAnxRVcRZCSD31OdA0A8GGBYZoYM=,tag:oYQ43IYQF2jzyjH+XbHS2g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email)$
  version: 3.9.4
