# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:qhKhA6JzMJChSEDTllnU493N9fvrC6HIfBteEWz1BK46219q/bqbI4IeYQuZHc5Xs4za7g4kXQa4M4Aph2FTOEtSv5y4S6iTA/jJ+QME05h8rLmkdNs60hFDqktjN3/le7Ns8dMwV8Op/dxoR7EWE+PxOUPlGXDGn/epL4fhPg==,iv:xUr/X4j8MjSDUcI/SdDrhU+zF8UDPC6DhNzTLw4l5go=,tag:iYoUgQr1iu2DYEezEVnhuw==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:KrIVpZ3yJMUjiIvHPcB1f4Vdju1duq+aBvnLRhZfLvE=,iv:qGm2UKyvGUisflnTOHDSPbIR3f7x50mrj9ZMyGuxDuw=,tag:JrAbYOKeMhnZYhoKL04/3A==,type:str]
  HOMEPAGE_VAR_HASS_KEY: ENC[AES256_GCM,data:UUmmm8q6Nnljnz7u8sxP3qQe5I6PoMG3eP5eiAvVBxBTwZC9oEfXA+Oc1Prm/xQo6egrUVOGxoPTYYcHwK1k0yMRoeFgjb8X/D5tWcpnv7Ye0E+GciTgdTtSMarn1vg29xhkUNpizVfyRDH4Mo+EK6O3RS//JfwKlFngZxIyfWN7WuFRhp2eAof9F8LuPssvJb28B5fCud6OjHhnn6tZUc0D0IGwMUG2PRfS8eUzjTC2t7KqTBfl,iv:6IhwkSJAtt5TnmzS/dDNCCySFwOUAAr2J6fcrPVxTB0=,tag:6KvxmKah02rr8DXAOhqSyg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSXkzSkhteEYxRC9ZYlN6
        Q3NUSjJtdXh6VE04MDExZWlwZVYyMnNRazI0ClpsQnhGaDJzTzlySmtGTlhlUExm
        NWhjbHJFanZzdDBpT2Vjb08yRzJqTzgKLS0tIDM1TERnUEo0Rkx2REE0Uk1GNjln
        WWcweTZaWVJha2Z3T0pLYU15L245ZGMKBVQ7DrXfhNrH888FYI7E9E3Wrc89ePtv
        MpnhCNnzs0mzEPqSGMZ739Pok9CicwPjhg7OpnQYZuMDC5pDsMnTjQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-16T04:21:25Z"
  mac: ENC[AES256_GCM,data:iin5944h+eVRQtWRZDGkVjGgEvOjk3jfWmu+bBIYW/4dBhvtbCRQZEfEnpk2B8AkPCORExLbmqErUSw51BRuR4jmD0bhXk+CcnEihZkqqkdlBOdcet9ZkCYE1C2GsmzBpft4l0Bu3noO+kr/xX7H+tZBOvhKHJDK0Qnmgxe08rk=,iv:yJy5uQUc3LdbDX5eEjAGXGkJ9sfT1gjxTnsbRu1hcac=,tag:pptWUjQ0ZAP0juj+4ZZEoA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email)$
  version: 3.9.4
