# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:BEolr3QKB6M2ki1e1ZGTQCDLUBj+JSypU25+0sGeeHUZWBJzFP3uIvUz0VCA3h9VWiDfAdF4DyMxcFX1Yz3pCxx8kfSKaEMPtXspxcYCCorGoVEkLlr8PTzW+OW3zX3vAmSa1t91KeVqT0yq68/Uha0HRN22V+6DONdk4etIcg==,iv:zwndc4YsgsKTAAaYuxEz6vAq71gOqgsnT2kzhvMzspI=,tag:O7CErPv9uy7VuTWB6Uj+zw==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:BbqTlnpxY5zp3pmHm+e0xrOzGSOC1WeOcq+g2bBV+rU=,iv:Kb0FQkQSDvy151jbypGcgMDwhO5aRtXaYjlTK2bUv1k=,tag:qehPk4ohpHG5DO/LBBU5gA==,type:str]
  HOMEPAGE_VAR_HASS_KEY: ENC[AES256_GCM,data:39g6QtLOv0Sl3VhxncNT85fGaKHWmdV6dj9Pd295Hm0KL9w6T+hkubB4X76GNCqVbfbx1PUvIoFpFNcmoemZiWXJxCBiBEy3WXQqS5xP4HmVBLj8OnC/mJePb/ZClpTNo4clbYoltytaWonLGZ+rhfoHlDatCgZiF8xls2bfhIK9eoLR+E/A7G+q7ItzcEqOSs/pvWL5MVsTVY9qh+D04z0wrTHU8lXBmqQKCXUUtjuwXfZzxP5q,iv:5faLRrsVChqlhk/Dljz2jc/kTWOmbgkQhXKk2dzjTm4=,tag:Zfw0K2U7AQyYHItR8kbjFA==,type:str]
  HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:tgzit8E=,iv:YRhq4Np5Cfi9lfVf0Ql3+QZJPmbIpjvazqReCitlExo=,tag:L8knbi90/v38ShMMgSBnhA==,type:str]
  HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:8W9e031eIW63OJXUjBk6,iv:SU24GF4padrg6Idc85Ntws7DFOgpZIi85b0UVWqQiiw=,tag:eTKbj1PI1HKmzvCiHzFH1g==,type:str]
  HOMEPAGE_VAR_JELLYFIN_API_KEY: ENC[AES256_GCM,data:t6X62Ez3av1BuUsJoy5Sqx5d+xt0uPovoIbuT46srpo=,iv:kJzUHRgUHNRtfhlS6/xInfx8MT30L+WtGkQBqh7sUV0=,tag:Bb4sO8jEHqEBAyGNK9ZfmQ==,type:str]
  HOMEPAGE_VAR_TRUENAS_API_KEY: ENC[AES256_GCM,data:+N7+bqG01cfvFpStOA1p2xWkmLNQ4ZcInKBeL8tOnpcheEUB0ouCyv6k8aZSrAWZg0eftjzUjspcamHS39X0ph7H,iv:gLxY0nizhidxuzgULYu9PsZQJe5LzNzF4E1eiL+5KL4=,tag:svertVJ/Rj6Vw1g7dIhv2w==,type:str]
  HOMEPAGE_VAR_SONARR_API_KEY: ENC[AES256_GCM,data:V3ZfkrHWtQSm4zNMp8r0zhugVm4ts/dFNoCrAG1qi18=,iv:0tzQREj5/nrAYBswLBAc+eZh0Ex546+bXjX6I1t2ovc=,tag:sGKsKweG/XiW0JsRaaCP9Q==,type:str]
  HOMEPAGE_VAR_RADARR_API_KEY: ENC[AES256_GCM,data:K6jtYqRoImCHLTCo6DTBoWS1zMrWpse6U1n4cGwNwxY=,iv:jav968oRy0exUsCV0sWeSkNEN0Rf47avt4O3WGr61Kk=,tag:AxwYhPxNBjRvsgn18gnIjQ==,type:str]
  HOMEPAGE_VAR_PROWLARR_API_KEY: ENC[AES256_GCM,data:y1iZlfwlDiIHKu5DKRfkrkZnJfxQQ0ystY5JmydEFGk=,iv:aUwtVh3pAXUYPpzxYR8ba3rddPPEtl5neyLgEVuMp7w=,tag:rNwfFLmbOqffDfYatLw2zQ==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:y3Rrjyg=,iv:Plw0fWjIKkZ/ksBNgr3Bl6vPcM8MqQ7p6bwqJj08PSE=,tag:pQQN3JH/hV/gkU0ockidFg==,type:str]
  HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:jTfRVtW5JseVrz5lmp6i,iv:D/8N7YfAE14mwGLe9nWYkD7vs9xLrw2wFkC5roHbglU=,tag:7ouK/5/fWqKs/RyZpTS9/w==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:8PFgEnGExEN+KhUcvDUl4XfYZrUR,iv:41iGvhPNaH1KkCLQIkenA0kREbcGA77jd9V+3NwDGcs=,tag:bqq7yMce2k8zxy8pghsG+w==,type:str]
  HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET: ENC[AES256_GCM,data:R8hX3rL0AqIK31+ot1AAzBhUudUT0xMQQkIHJgIKepUXCL+r,iv:jT8ko9xQAkSqEIVmaRCgkiytZWz8QeqIQyYeKUECU5Q=,tag:XGaQLE7fxOUrk8WPXPhKBA==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS0pRcldXTkN0TFZmWlFj
        MTh1bFZTYWpSTDlvc2tyeFh5d0gyTU9BR0JzCmswWmxCdkdaUzF2N1RxWWVDaXZn
        UGNmeGVzSm1sbkFJbnRaSzZRa1NlaGcKLS0tIFc1V2FQUndpYldLMTFPVFZibTFX
        SEZHWFBIZmFOZ1Zpb2Z3a3hkRU1KSzgK35HbGU3nPziG56/R1zava37UibEp0znv
        m/RFFxK5GPiBXRDKAzq2x3sZ4/1Fr7kloJ/5WeQ3GmiMeaEMy8RQNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-13T23:38:02Z"
  mac: ENC[AES256_GCM,data:oXtP29HfFu1Q4OkSttdebgy8i4WwV4lH4KQqP+6e4Kl9Wzqg+CGmLwrjrKBEPf4hxvaNZqtHKBDCRkAqwnygfdQh+WRZVMIrKAUIr3eUQLKonMEVr8GntnLsxq0VDffLnlKvW4Ys5IzBqxcNkxUetFOdk1Z+ObP6Ds6Hf31VoNw=,iv:ate7QXeYJXTKGnrUauFfre8DuEOxZv0ox95WbNVMldc=,tag:Ubo/U5PgidAMsfer6fihOg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.10.2
