# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: homepage-secrets
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
stringData:
  HOMEPAGE_VAR_UNIFI_URL: ENC[AES256_GCM,data:sJENi4YU+74/NLckGqcarfExJl9kdlp9lOowimrzR/5BgtqHDq3Xxq/uiSjnHwU3rjlydluEaUz0zgwlXBbH4IH4dzk5oYfo+ZkGzJUSXz7vAEBKuuPbw6cy93Ipca4c6t9rvZgV/o20GCAIm1BuDwstJYJGhtnLgfhmONZBWw==,iv:8jKz4nQGDP4diXonfP4RXhVy60+e88dlx4xADdHZrSE=,tag:l3ENrzT2QvJXBkSohu+KjA==,type:str]
  HOMEPAGE_VAR_UNIFI_KEY: ENC[AES256_GCM,data:Meh8jsOfXDmgNGDQGJOGo8XtEfouV11DPv98YiDkZ4A=,iv:3qF5mmODgMDcocQWOqtQ7xvQzWx+LLbUPbJYyB0KRj8=,tag:tvzDCov4G5uIfxzejyVAeg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dXF4RktCV0tFVzhuRVRz
        UEdmS2tYSHhnTlk0bTNBWmR2cUkxMUFsNlVJCkJvMDFuYksyM0dGd2NQMVFHZVJs
        Z203clNYYjU2MDBleXpSeW8vVkJRbVEKLS0tIEhsMXVvNzBvTms1VDVpWGZRbDJj
        NTdPaCtCZXNEbmlWaEF2UlFPM2x2UWsKWbgKYbvge1cufJf4xWux/jLjTUif/2R2
        Tp5EyWCCD1JKesn4YM+2L0RJBCfIXlCxMbOGtvhcEmYYea7jPnopMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-13T07:58:55Z"
  mac: ENC[AES256_GCM,data:Tv9DCXaNqKGK+TSI3avUfmZb3qR9L5mm9KmsFJar3bVg98Wir6ngCJLaBQhiaIfYVo2z5lTo1JCy2GRAtACO97I/fmb1/bfOXKsYPptUg260iFAa49g6+5qJY1ADWMt05vX+doSNc7uKJogDVqyoFpIkR2Knq8MACsmZglmVSEo=,iv:bRqvur7ac/IGLLr9taMZFvS5s5thrkziO2Nrf3TGiDQ=,tag:RYm6XU6YMNki9cNUlqRx4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email)$
  version: 3.9.4
