---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - clusterrole.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - homepage.secret.sops.yaml
configMapGenerator:
  - name: homepage
    namespace: homepage
    files:
      - config/kubernetes.yaml
      - config/settings.yaml
      - config/bookmarks.yaml
      - config/services.yaml
      - config/widgets.yaml
