---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./recyclarr.secret.sops.yaml
  - ./release.yaml
configMapGenerator:
  - name: recyclarr-configmap
    namespace: media
    files:
      - recyclarr.yml=./config/recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
