# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
  namespace: media
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:TADmVatBY2USGlDf9BvFjXqrDxcq4rvjzvA8RKQOo5g=,iv:JjXv1lCH8Zd2B3aaeF5ZA6XQThjcLVmsSQodinZUIsk=,tag:zRV7kFb10UeQycYtdilecw==,type:str]
  RADARR_API_KEY: ""
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V09VQWxObForMmhkUW12
        ZDY4b3V6ZHU1QXlEN1lTaHFCU1F3R05HSldZCnowd20xdUlnUWMzakU0WUY4bTVW
        dkYwTDJVUlA4NUUyTCt5cTEwK0U0NHcKLS0tIGZKdlpNYkJ6cCtOTXZiOFd3WUJV
        dFJRTXV2K0ZrcGlhQnNldXErekZwQnMKRXRlMC7BOLf1MGqwyg8qaSw32vw0lH3/
        0X5bnp1DOfgx32b+vUOUIQKN//w21fjQUtKXGowXZ3/TwssREjI26Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T20:35:56Z"
  mac: ENC[AES256_GCM,data:msjIJgqbHmXgsHAgpYwGaGgfc7kbd5Uv8k7Y4C6fXTiLbkYI7DHfIpPAqpTNgrs8wnMprDqMu2clvQtB/1EnxESZHlopdastSucowocwb8a1XoKw1OCzTj17ZHZZtMU5bNKlfL70QYrbOIV08eaZosl6E65bFN4Puavu0DiMjT0=,iv:hxbHMYO7ZNEG5Xmk1vy2ol64WR3gdNELIBKuAifK1Dw=,tag:TlWz0YcGX0Com5YWzQkILQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.10.2
