---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: axis
  namespace: traefik # needs to be in the same namespace as the ingressroutes & middlewares
spec:
  secretName: axis-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.axis.scottmckendry.tech"
  dnsNames:
    - "axis.scottmckendry.tech"
    - "*.axis.scottmckendry.tech"
