# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-oidc-credentials
  namespace: monitoring
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:y0Sy4Yv1BoaP/yGAZpw4EHxKv8BicIUDi5ncRW7vDTGmi7sK,iv:ox11a4DDxCjtIh2PYQxGmsmUal1MMcFovYCEjKEvSOA=,tag:/ZrkG/l/tsV042yuwyC+ng==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7ORdFcU1DHBJb5ww46mMdolGREC8DtsC6JYNF7FAy4hWoVBHAz8pPe4W56aoiZrx1lCP+S4APe8AqRej91IpSQ==,iv:ClglE7hjnfwaPWdTVr3c0RFmMjJVOJuMp+3puDwPiBw=,tag:+FPd/IbhuVkNKNZGIdS0Lg==,type:str]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:JTMNMoU=,iv:Ngsl4YFaEVR3N1BCcFK3qMvDcxtuBoJr9PdPxyQt3J0=,tag:8C3GL0kAvQfWZgMgtzg0wQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:948xQ10Zlr8f03S9voj+,iv:UmoeXDiqbCnOoMXNvNKFN/emlodqdiDpDBcjKnveTkA=,tag:CRIjCuWoPxco2WjgC3aTiQ==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaHhaMUpjV1B0NlFZUFY5
        TFdxUEMzaHVBUWdoZ0NWNzlRVUN3K1I2WUFNCkdHbUVqVkdoWGtlTXJ2WkZvTitk
        TVdweURiQ2RhL2FzM2VSeVRhcXh5a1EKLS0tIEhQbk5HYlNFVWMxUEZXRlRtM1FO
        aHBjOXk1UlJVWjM1SW83cmVtOEI3OUkKe1EmP84rDzl+Qf5m/w2hggYZmReQWE1w
        0fm1TZ6dduEa1VeZhUqzqYr+5z8RycRfxK0NVIT4EZjexwvP0zvDjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-09T07:33:00Z"
  mac: ENC[AES256_GCM,data:c0Ody00R0PQuwb1BWDY99hHphZDWgIdlfSB/q/Y7O91yT/vIlzNM3Giy9l72PCIcpRhVtAD7kKpnuZVRTFW24M9jbFElpmlhKn1F4PozNpgnjS8E+Mot3pgf3CLuScOjS0o/WXUNJnWYe2YkRWPjoLiIHQHfiimTH0tjK7bM0wM=,iv:ufSYmSU+ttc79vj2C6JTQn4gbBIerZzfm+lkbEWEBfE=,tag:E+RDq2RtudmYcUcroEPrCQ==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.12.2
