# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-oidc-credentials
  namespace: monitoring
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:MpAR0keT2odOr6YPLynM/SvFiXroUm35Z+OJ3NVnQiD2bTfT,iv:I6L8p8bKcztuu+0LIdpfjDpMWaoFbJ0So4B4zT77+Ec=,tag:5yY9PzC29zrG/C62IFW2pA==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Jhz/SQ2h2bvgBz7OgUc9jjDe8zw6t2UGh2STKSTS14H4K587PY9GonBau3koFWTSGcFo6w2yPWxq1U+9TQRqDA==,iv:zroJ8+UA2/JAggZL55pKnNVQPGggNhC61Vhy5TWxxy0=,tag:fQ4vdc7mSxAYlLNz4umj+w==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlLzRkTDlScXpEZW1za3JG
        TzFCMTZtOGVkUE82YjFBaFZzVmorMjhPSzA0ClEycW02eUk2Yldwbm5LRDl4aWp5
        ZG41Vy8vOG1TK05IQ1lLanl5MnluQmcKLS0tIG1NbUQrREZzMXJOc3FZSU8wMnl4
        ZkRoTFZvWVVQazY1RFhCcnFPeTJZY2sK6daIMcGTh1Z8AM9Xf2cfXQKpSwYGZ5P/
        bGFY/ZRVGaoEPFS9DqImhBlRslfq2ZUuLH5zvymlVXI2JEdif/a+iQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T08:38:21Z"
  mac: ENC[AES256_GCM,data:kgB88uvoKzcR0YfZDwiCByedJ+199eG91ODt9+eW570cYc+lU1YEWND9HXRadY6xRgBAA/25gFKMOUwH0cZymkSKe8rg+V1UhvKJLOQt9gIRjdWVxXW1hXTZ7FK6KLET10hWb4rHWUjMOwV2Kzlde11cgTkqHYFJ7tF3k8VCCc0=,iv:m3EH6IoL+S2qU0AabicmztIleRhKL36Ly7BX3whbEg0=,tag:zRQLAG4ZHEJIesJANPBfUQ==,type:str]
  encrypted_regex: ^(data|stringData|email)$
  version: 3.12.2
