# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-media-prowlarr
  namespace: media
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:CXR2D8yF1Vdqw3F5buizHP5/7HaryMbInFVfT5m3/AlWcOd0typOIo8gxi3C01KWRaikZU0hdSPNeUCWwQ==,iv:Imk9lYobEhOUb9lGa4v+5J+HEtGUKJ+L9lTwVMM6vTw=,tag:Omtk/r5O0oOxoSilYiF23g==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:L+oxZOig1J5QIKMwgGpsvUccu/onc8TbrGAsq9QpzTs=,iv:65N2cjHlH4QBpeOjr0lle4To6RozqsvDCvYapjLmVTk=,tag:m64TsTTgkEu2RyiRsTuhUg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HInpIMrhmSi/8HQ+sdnZ09T0avR2+mgzmw==,iv:0MxFvx8uZ1aH8PCunT1mUJKGk1OBhrNHUr02rCk+D48=,tag:+P17WZTxqQHn2yf+ZMqXow==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9d98lhNAKL9w+YNbFfuYviA161hRV51CesmRrxDnIA==,iv:hq21ytptPSWxA2UQ3OGZ1HAuPBK5ocl2Upw2qcPgrYQ=,tag:dUjHANQnZL6xsYJv6ehIUg==,type:str]
sops:
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVTN4dExtZHBGZ0dwaDlu
        N253WFY1QjE4V3M0SlNsNWhQcEh1MWJpQlJrClpBZU1naGVzN3kwNmVUaHRMWjBL
        TTBReVVHWGZXOFNoR29ETi83SnUxUTQKLS0tIGdZOWUxV3F0dmpnckJTODlySEcy
        dmNGSWNLdUEvemcrUTF3aUVXdXBaQTgK57ZWqvJXH50qYyEVXKL9M2ofRYyOHz5x
        3zKRt8GnPWrahEQ74no9D6/QtTH702EMk35gaNFwKZDHSVq7lUeBvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T19:23:17Z"
  mac: ENC[AES256_GCM,data:ogcbM3v4m8KZ3qRp8FgpP5KkXSKoxFPiUdlOKX4cqxl/tYoPiMBTsTSFLttgG4mtYkwaiptAM622iHyXsvEE9rWfXdm2obLhVcnD8z3aksXDbWlEpXKarbe2W7DI69gFYKAoNVaBWv5jyjdOt8NhwbHts4spcyzWmfWdFlvIsms=,iv:JBp+fCOxxKvxZhkLoA3KlJjQLUK/mqk5LVZ+CYmHLiE=,tag:Vq2T8o45BKiav+Gs+WS0dg==,type:str]
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.10.2
