---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant-home-assistant
  namespace: home-assistant
spec:
  sourcePVC: home-assistant
  trigger:
    schedule: "0 1 * * *"
  restic:
    moverSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
    pruneIntervalDays: 14
    repository: restic-home-assistant-home-assistant
    retain:
      daily: 7
      weekly: 4
      monthly: 2
    copyMethod: Direct
