# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-home-assistant-home-assistant
  namespace: home-assistant
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:kalc4/rolNfc6Z7Pwi/ZYCg73E9Y9G6Ql8u9XBWIHbYaClhLCacrHU2nAdNSySzuNKocX6ZiaCnE1m3xfxvjWJ48IQPQv+tvpu0Uhw==,iv:mPDco+Y+QF7qgRkiLx+I1408WYL8jsEDZKF7CVNINF4=,tag:y+WIRVqy1TCeYfWJ99S+hQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:EMlmaomWugBoUw8HJuto5e+6hkmM8gW+Xy3Csd3bDTU=,iv:5tEIVEtEnXe/Ko5yfgCeZhClwhYIkV6H3R1DQ+d4Mqk=,tag:f70SfYKiIX5Dh1yxNWhNVQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cSfePeQdXJt5wRcs1+pFuPRSMN3IVgCpIg==,iv:DX8PJkb8F8c/hKiUdrc3toqCdCV9kYkeEpVSSX4xOho=,tag:KphhuVaqmb9w6e5/9/dvWw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:R/FLAetPFsO/wJl75vDn4LtTb6ym5Z1iZQq6xanmhg==,iv:oKL2rKEWfX4JSWhFP1fxEEY0C0YX3Wzf5R2Q6Uwb63E=,tag:p/ZFeiTStY4Edb8wBqTs9A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU2tFTlAzUHpuZXcwSklB
        WGZlNnpiUURRVStSNDhGZHdxRTU4T2ZyblZvCmhCWWpSWVh4NWNqV3hQOXI1anJw
        SmU5WGd2ZmdkZmw5WmtyYnJZNHVBdkEKLS0tIGExNjNyNXk2enVhMHhnaEdMaCtr
        eFNUdmE2ZnByb3E1VWNkRXBGV1hobVEK7xZAP8B9Zspz65AQc1RXT8J93Ss+ynr9
        YSxNdLnMzRtiB+HHLkrufk76jztoDg4j+6mfw+jQJ0QO/zP+dE1e6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T17:55:07Z"
  mac: ENC[AES256_GCM,data:URLuhdJZbBwxPHKZBMA3CcQnxm4sdgMDvTfGBKgk5OgYwICy9Yhg51X6BggOxvPro8X5NimsnDisaTJ11f50XTHYk53xJoqqkW2XzRHjK2j1ZcV66iGiMp+yr2KflY8uGZclY0WnmzO2A0G8gDJAgaHOzaFNxYwrVUvNl5UqHA8=,iv:TkBAqxnzHS7ztsHdluS50n9Iee3NIjztdyLO7cogIPU=,tag:fF/c9yh/6wRNcYnUj/4RMg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.9.4
