---
# https://gethomepage.dev/configs/services/
- Networking:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_URL}}"
        siteMonitor: "{{HOMEPAGE_VAR_UNIFI_URL}}"
        widget:
          type: unifi
          url: "https://10.0.0.1"
          key: "{{HOMEPAGE_VAR_UNIFI_KEY}}"

    - Traefik:
        icon: traefik.svg
        href: https://traefik.axis.scottmckendry.tech
        siteMonitor: https://traefik.axis.scottmckendry.tech
        widget:
          type: traefik
          url: "https://traefik.axis.scottmckendry.tech"

    - TrueNAS:
        icon: truenas.svg
        href: https://truenas.axis.scottmckendry.tech
        siteMonitor: http://10.0.6.1
        widget:
          type: truenas
          url: "https://truenas.axis.scottmckendry.tech"
          key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
          fields: ["load", "uptime"]

    - Proxmox:
        icon: proxmox.svg
        href: https://proxmox.axis.scottmckendry.tech
        siteMonitor: https://10.0.20.1:8006
        widget:
          type: proxmox
          url: "https://10.0.20.1:8006"
          username: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_ID}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_TOKEN_SECRET}}"

- Apps:
    - Home Assistant:
        icon: home-assistant.svg
        href: https://ha.axis.scottmckendry.tech
        siteMonitor: https://ha.axis.scottmckendry.tech
        widget:
          type: homeassistant
          url: "https://ha.axis.scottmckendry.tech"
          key: "{{HOMEPAGE_VAR_HASS_KEY}}"
          custom:
            - state: weather.forecast_home
              label: "{state}"
              value: "{attributes.temperature} {attributes.temperature_unit}"
            - template: "{{ states.light|selectattr('state','equalto','on')|list|length }} / {{ states.light|list|length }}"
              label: "lights on"
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }} / {{ states.switch|list|length }}"
              label: "switches on"

    - Home Assistant Code Server:
        icon: visual-studio-code.svg
        href: https://ha-code.axis.scottmckendry.tech
        siteMonitor: https://ha-code.axis.scottmckendry.tech

    - Actual Budget:
        icon: actual-budget.svg
        href: https://budget.axis.scottmckendry.tech
        siteMonitor: https://budget.axis.scottmckendry.tech

    - Crafty Controller:
        icon: crafty-controller.svg
        href: https://crafty.axis.scottmckendry.tech
        siteMonitor: https://10.0.6.1:30146
        widget:
          type: minecraft
          url: "{{HOMEPAGE_VAR_CRAFTY_SERVER_URL}}"

- Monitoring:
    - Grafana:
        icon: grafana.svg
        href: https://grafana.axis.scottmckendry.tech
        siteMonitor: https://grafana.axis.scottmckendry.tech
        widget:
          type: grafana
          url: "http://grafana.monitoring.svc.cluster.local:80"
          username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

    - Prometheus:
        icon: prometheus.svg
        href: https://prometheus.axis.scottmckendry.tech
        siteMonitor: https://prometheus.axis.scottmckendry.tech
        widget:
          type: prometheus
          url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"

    - Alertmanager:
        icon: mdi-bell-alert-outline
        href: https://am.axis.scottmckendry.tech
        siteMonitor: https://am.axis.scottmckendry.tech
        widget:
          type: prometheusmetric
          url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          metrics:
            - label: Active Alerts
              query: alertmanager_alerts{state="active"}

- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.axis.scottmckendry.tech
        siteMonitor: https://jellyfin.axis.scottmckendry.tech
        widget:
          type: jellyfin
          url: "https://jellyfin.axis.scottmckendry.tech"
          key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
          enableBlocks: true
          enableNowPlaying: false
          fields: ["movies", "series", "episodes"]

    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.axis.scottmckendry.tech
        siteMonitor: https://sonarr.axis.scottmckendry.tech
        widget:
          type: sonarr
          url: "http://sonarr.media.svc.cluster.local"
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"

    - Radarr:
        icon: radarr.svg
        href: https://radarr.axis.scottmckendry.tech
        siteMonitor: https://radarr.axis.scottmckendry.tech
        widget:
          type: radarr
          url: "http://radarr.media.svc.cluster.local"
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"

    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.axis.scottmckendry.tech
        siteMonitor: https://prowlarr.axis.scottmckendry.tech
        widget:
          type: prowlarr
          url: "http://prowlarr-app.media.svc.cluster.local"
          key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"

    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qbt.axis.scottmckendry.tech
        siteMonitor: https://qbt.axis.scottmckendry.tech
        widget:
          type: qbittorrent
          url: "http://qbittorrent.media.svc.cluster.local"
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"
