---
# https://gethomepage.dev/configs/services/
- Networking:
    - UniFi:
        icon: unifi.svg
        href: "{{HOMEPAGE_VAR_UNIFI_URL}}"
        description: Dream Machine
        widget:
          type: unifi
          url: "https://10.0.0.1"
          key: "{{HOMEPAGE_VAR_UNIFI_KEY}}"
    - Traefik:
        icon: traefik.svg
        href: https://traefik.axis.scottmckendry.tech
        description: Reverse Proxy
        widget:
          type: traefik
          url: "https://traefik.axis.scottmckendry.tech"

- Apps:
    - Home Assistant:
        icon: home-assistant.svg
        href: https://ha.axis.scottmckendry.tech
        description: Home Automation
        widget:
          type: homeassistant
          url: "https://ha.axis.scottmckendry.tech"
          key: "{{HOMEPAGE_VAR_HASS_KEY}}"
          custom:
            - state: weather.forecast_home
              label: "{state}"
              value: "{attributes.temperature} {attributes.temperature_unit}"
            - template: "{{ states.light|selectattr('state','equalto','on')|list|length }} / {{ states.light|list|length }}"
              label: "lights on"
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }} / {{ states.switch|list|length }}"
              label: "switches on"
    - Home Assistant Code Server:
        icon: visual-studio-code.svg
        href: https://ha-code.axis.scottmckendry.tech
        description: Edit HA Configuration Files

- Monitoring:
    - Grafana:
        icon: grafana.svg
        href: https://grafana.axis.scottmckendry.tech
        description: Dashboards and Monitoring
        widget:
          type: grafana
          url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80"
          username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
    - Prometheus:
        icon: prometheus.svg
        href: https://prometheus.axis.scottmckendry.tech
        description: Metric Collection
        widget:
          type: prometheus
          url: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    - Alertmanager:
        icon: mdi-bell-alert-outline
        href: https://am.axis.scottmckendry.tech
        description: Dynamic Alerts
        widget:
          type: prometheusmetric
          url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          metrics:
            - label: Active Alerts
              query: alertmanager_alerts{state="active"}
