---
# https://gethomepage.dev/configs/settings/
title: AXIS
background:
  image: https://w.wallhaven.cc/full/kx/wallhaven-kx5rpd.jpg
cardBlur: xl
theme: dark
color: slate
hideVersion: true
disableUpdateCheck: true
