apiVersion: v1
kind: Secret
metadata:
  name: headlamp-oidc
  namespace: headlamp
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:GIORDosSp/g9KAMOLAarW3518yVpfPiKChvocjJ0TDAoXXzX,iv:zWeOU0u5gY6k/JD4x2xm40XcvMDI2R/hMyyINzIgKaY=,tag:JaNDeMH9fQvBELie2r6TQQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rKi9hI4MuxoEHBCp5DwKFhpbT44g3/pAs7ZpmGj0cZfhr66YrbXQmNboI3uEzg35fR6VfgjSEMblpI3Gus0Lpw==,iv:DMoFGQuXmHxSk68HN1+cifv4lUgsDDTuCyzNcbaoZkw=,tag:9Dyc2i0k/zac8y9wcLCctw==,type:str]
  OIDC_ISSUER_URL: ENC[AES256_GCM,data:0ws7odsOXxNHuhsUqVeLgDXPIxpVvAP2HLwpeqclV0RFhpV9,iv:FbSxzktb8c4hPF8eSbkMG3BEbTk/fYSf0rWTeMI3ljQ=,tag:IMCc4MfpowzwcqOvygBA1Q==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:YjMbUaFjN/xQyqUhuX9uJ15n/OE=,iv:skXcK/W1eYE+DWyYSIp25mWYONvHnv+bMOd7up62P7w=,tag:J33zk2S2UG4o4HKKcyP57Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueWZlTU03R3JrRXNtQ0tp
        RjN6TmdwQnZjMTZQNEJDbG1iL2xxeGVVeTNvCngyZmFSWjJ4S21mSkJpaG9pVXkx
        eTJndm5yaXMvUlphMjlzaDVvTHJNLzAKLS0tIFRzc3dIaVExb2o2RVpPd1c1SkFn
        TnNMTzQwS2xkaTJzWkdBZUVxbFdJUlUKzy3DbvYwNszz2ThJ0RzNiw1CYiBf/K0S
        /NOtr2pyzvZD/lnRgs91hoNux2PXTbjc9IAtfxg6o1RNvRqKyVKe8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  lastmodified: "2026-05-17T04:30:59Z"
  mac: ENC[AES256_GCM,data:bm3Le3KeBVSvALMZjXIw77knDIkq7N7R1ah3BFWnsXzxd3GUFqSaFXDgKljE1PdXa2JfFKAv9fvinygxg/SwjIx9VucGZ58flzPHAFAw+Zw1hE9dy4Fviwnj7OvFLoKjqE9hmLWMaeSyiPanFGW/ZsW6/4ljm0g5h7oALHuhQ4g=,iv:YgP4bClUkamLLg8lzlqSYF3FGq7ZjpMsX7+VlJeRAP8=,tag:BrOtCfZu4SXHWr5vYI2nzg==,type:str]
  version: 3.13.0
