# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/secret.json
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: restic-ccinvoice-ccinvoice
  namespace: ccinvoice
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:LcJHV5kRf5+w/AWoNUeSUjFVgrx8ZiP1YvCHZgqsQrGwNoXYytmPIY0ENI7q6flPGHIbk8YoueDAJGAm6MNOPFtu,iv:lIunLI6p0hsELq3rCByC1t6qVnA38pgOyWSAVXAJGFI=,tag:bLrPs449W2MCEsQBhYklBw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:6tPA918YTE2vhah4Rg4hqAYXkKfzusEP3extF3j2BF8=,iv:fE9mo0yedEtyNx/Ufe79b1mFSVkcWggdYOf7avYtybY=,tag:RqKFEBj/QAr4DCvOhgvOfA==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RS5Tm+FL3fH30MwW9ga5Il/u/506fkEEAg==,iv:guePuq/xWkBP400fHMvqdY2HJD4DE7LOUzWcX7Xj9pE=,tag:ZkxDg3RJ/LDbL0cP0YgFjQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/leEx/FDAvfhNaWOxQNaM5Mtv+Jbvp+kdsvYLuq5uQ==,iv:CSG9L/uAB2b8JvwX66qaeyw/G8ilrJjyKFJh08oGicE=,tag:DM1nufX5QoAHTT84TWDJaQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ht2mpnqakafawr4akvukz2ketzdlwuwkhdzwsy8hl7rwfkhkh90qp36und
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWprVnFXeFNOcUE1V3FH
        ZFd3UTUwWVBIaWZ4NDdsZlAzZW9RRGZRQlhjCkFxL3BQaFBCTGxHZU1zTUJhb3I3
        bTdUT25mNG43YndJNy9WWWRvUHlROWsKLS0tIFp4TGVSTlpIeFRUSUxQUStGaHVI
        TGVwZ3lGUzVCdFpBWm44WEkrSE1HWm8K7igmamO7bJPa/y1BjfJEjEsD5PHjwRLA
        q8LJDlTlUw6NMFcgKDPRewcBZZ7LE07C3BfXqPydyjYvdC224nTryg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T17:55:07Z"
  mac: ENC[AES256_GCM,data:rs4rtzdb1ihziWfTfG1BpONzbGNLe5bARfHGtYONJS04u7FPJmGMCsERMuyV+fLJlPUzkRX8UaEU7YC8lChPy3WCNMrsTbDMfkDhB7Wxu6aQgBNkmE93WnCPJLFhf9inZZ4hDcB7DsXdyIMhI7ATOS1t220eF3UQnG4EhlgifuA=,iv:zWseDP/iM5s1yp5So4WNKEmopGnUKnRf/3F4ExTt1Xo=,tag:rRaRzPzZ2UAXpFF40yc+yg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|email|host|apiKey)$
  version: 3.9.4
