---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - repo.yaml
  - release.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - certificate.yaml
  - https-redirect.yaml
  - clienttrafficpolicy.yaml
  - securitypolicy-ipallowlist.yaml
  - securitypolicy-forwardauth.yaml
  - backendtrafficpolicy-ratelimit.yaml
  - external-routes.yaml
