name: CI
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
