name: CI
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
